/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Chacha20_H
#define __Chacha20_H

void
Chacha20_chacha20(
  uint8_t *output,
  uint8_t *plain,
  uint32_t len,
  uint8_t *k,
  uint8_t *n1,
  uint32_t ctr
);
#endif
