/* This file auto-generated by KreMLin! */
#ifndef __Hacl_EC_H
#define __Hacl_EC_H

#include "kremlib.h"
#include "testlib.h"

void Curve25519_crypto_scalarmult(uint8_t *mypublic, uint8_t *secret, uint8_t *basepoint);
#endif
