/* This file was auto-generated by KreMLin! */
#ifndef __Hacl_Policies_H
#define __Hacl_Policies_H


#include "Hacl_Symmetric_HSalsa20.h"
#include "kremlib.h"
#include "testlib.h"
#include "Salsa20.h"
#include "Poly1305_64.h"
#include "Curve25519.h"

uint8_t Hacl_Policies_declassify_u8(uint8_t x);

uint32_t Hacl_Policies_declassify_u32(uint32_t x);

uint64_t Hacl_Policies_declassify_u64(uint64_t x);

FStar_UInt128_t Hacl_Policies_declassify_u128(FStar_UInt128_t x);

uint8_t Hacl_Policies_leak_byte(uint8_t *b, uint32_t n);

uint8_t Hacl_Policies_cmp_bytes_(uint8_t *b, uint8_t *b_, uint32_t len, uint8_t tmp);

uint8_t Hacl_Policies_cmp_bytes(uint8_t *b, uint8_t *b_, uint32_t len);
#endif
