/* This file auto-generated by KreMLin! */
#ifndef __Hacl_Symmetric_HSalsa20_H
#define __Hacl_Symmetric_HSalsa20_H

#include "kremlib.h"
#include "testlib.h"

void
Hacl_Symmetric_HSalsa20_crypto_core_hsalsa20(uint8_t *output, uint8_t *input, uint8_t *key);
#endif
