/* This file was auto-generated by KreMLin! */
#ifndef __Salsa20_H
#define __Salsa20_H



#include "kremlib.h"
#include "testlib.h"

typedef uint32_t Hacl_Impl_Salsa20_u32;

typedef uint32_t Hacl_Impl_Salsa20_h32;

typedef uint8_t *Hacl_Impl_Salsa20_uint8_p;

typedef uint32_t *Hacl_Impl_Salsa20_state;

typedef uint32_t Hacl_Impl_Salsa20_idx;

typedef struct {
  void *x00;
  void *x01;
}
Hacl_Impl_Salsa20_log_t_;

typedef void *Hacl_Impl_Salsa20_log_t;

typedef uint32_t Salsa20_u32;

typedef uint32_t Salsa20_h32;

typedef uint8_t *Salsa20_uint8_p;

typedef uint32_t *Salsa20_state;

void *Salsa20_value_at(uint8_t *m, FStar_HyperStack_mem h);

void
Salsa20_salsa20(
  uint8_t *output,
  uint8_t *plain,
  uint32_t len,
  uint8_t *k,
  uint8_t *n,
  uint64_t ctr
);
#endif
