/* This file was auto-generated by KreMLin! */
#ifndef __Salsa20_H
#define __Salsa20_H



#include "kremlib.h"
#include "testlib.h"

typedef uint32_t Hacl_Symmetric_Salsa20_h32;

typedef uint32_t Hacl_Symmetric_Salsa20_u32;

typedef uint8_t *Hacl_Symmetric_Salsa20_uint8_p;

void
Hacl_Symmetric_Salsa20_crypto_stream_salsa20_xor(
  uint8_t *c,
  uint8_t *m,
  uint64_t mlen,
  uint8_t *n,
  uint8_t *k
);

typedef uint32_t Salsa20_u32;

typedef uint32_t Salsa20_h32;

typedef uint8_t *Salsa20_uint8_p;

void
Salsa20_crypto_stream_salsa20_xor_ic(
  uint8_t *c,
  uint8_t *m,
  uint64_t mlen,
  uint8_t *n,
  uint64_t ic,
  uint8_t *k
);

void Salsa20_crypto_stream_salsa20(uint8_t *c, uint64_t clen, uint8_t *n, uint8_t *k);

void
Salsa20_crypto_stream_salsa20_xor(
  uint8_t *c,
  uint8_t *m,
  uint64_t mlen,
  uint8_t *n,
  uint8_t *k
);
#endif
