
all:
	$(FSTAR_HOME)/bin/fstar.exe Spec.Lib.IntTypes.fst
	$(FSTAR_HOME)/bin/fstar.exe Spec.Lib.IntTypes.fst Spec.Lib.RawIntTypes.fst
	$(FSTAR_HOME)/bin/fstar.exe Spec.Lib.IntSeq.fst
	$(FSTAR_HOME)/bin/fstar.exe Spec.Lib.IntVec.fst
	$(FSTAR_HOME)/bin/fstar.exe Spec.Lib.Stateful.fst
	$(FSTAR_HOME)/bin/fstar.exe Spec.Lib.IntTypes.fst Spec.Lib.RawIntTypes.fst Spec.Lib.IntSeq.fst Spec.Lib.IntVec.fst Spec.Lib.Stateful.fst

