USER_TARGET=
USER_CFLAGS=
USER_C_FILES=/dist/generic/testlib.c
ALL_C_FILES=Hacl_Impl_P256.c C_Endianness.c Hacl_Impl_ECDSA_P256SHA256_Verification.c
ALL_H_FILES=FStar.h Hacl_Impl_P256.h C_Endianness.h Hacl_Impl_ECDSA_P256SHA256_Verification.h C.h Hacl_Spec_ECDSAP256_Definition.h
