USER_TARGET=
USER_CFLAGS=
USER_C_FILES=/dist/minimal/testlib.c
ALL_C_FILES=Hacl_Hash_SHA2.c Hacl_Impl_P256.c Hacl_Impl_ECDSA_P256SHA256_Verification.c
ALL_H_FILES=FStar.h C.h Hacl_Hash_SHA2.h Hacl_Impl_P256.h Hacl_Impl_ECDSA_P256SHA256_Verification.h Hacl_Spec_ECDSAP256_Definition.h
