/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: /Users/bhargava/Desktop/repositories/kremlin//krml -funroll-loops 8 -warn-error +9 -I /Users/bhargava/Desktop/repositories/hacl-star-dev//lib -I /Users/bhargava/Desktop/repositories/kremlin//kremlib -I /Users/bhargava/Desktop/repositories/hacl-star-dev//specs -I . -I /Users/bhargava/Desktop/repositories/hacl-star-dev//code/experimental/aes -I /Users/bhargava/Desktop/repositories/hacl-star-dev//code/experimental/gf128 -ccopt -march=native -fbuiltin-uint128 -drop FStar.UInt128 -fnocompound-literals -fparentheses -fcurly-braces -tmpdir aesgcm-aes256-m32-c aesgcm-aes256-m32-c/out.krml -skip-compilation -minimal -add-include "kremlib.h" -drop Lib.Vec128 -bundle Hacl.AES_256_GCM.M32=*
  F* version: 7c70b890
  KreMLin version: b511d90c
 */


#ifndef __Hacl_AES_256_GCM_M32_H
#define __Hacl_AES_256_GCM_M32_H

#include "stdint.h"
#include "stdbool.h"
#include "lowstar_endianness.h"
extern uint32_t Hacl_AES_256_GCM_M32_aes_gcm_ctx_len;

typedef uint64_t *Hacl_AES_256_GCM_M32_aes_gcm_ctx;

void Hacl_AES_256_GCM_M32_aes256_gcm_init(uint64_t *ctx, uint8_t *key, uint8_t *nonce);

void
Hacl_AES_256_GCM_M32_aes256_gcm_encrypt(
  uint64_t *ctx,
  uint32_t len,
  uint8_t *out,
  uint8_t *text,
  uint32_t aad_len,
  uint8_t *aad
);

bool
Hacl_AES_256_GCM_M32_aes256_gcm_decrypt(
  uint64_t *ctx,
  uint32_t len,
  uint8_t *out,
  uint8_t *cipher,
  uint32_t aad_len,
  uint8_t *aad
);

#define __Hacl_AES_256_GCM_M32_H_DEFINED
#endif
