kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: test
  image: rust:latest
  commands:
  - apt update -qq --yes && apt install -qq --yes opam aspcud ocaml clang
  - opam init --yes --bare --disable-sandboxing
  - opam switch create 4.09.1 --yes
  - eval $(opam config env)
  - opam install --yes cppo ctypes ctypes-foreign dune zarith
  - bash .ci/script.sh

---
kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
- name: test
  image: rust:latest
  commands:
  - apt update -qq --yes && apt install -qq --yes opam aspcud ocaml clang
  - opam init --yes --bare --disable-sandboxing
  - opam switch create 4.09.1 --yes
  - eval $(opam config env)
  - opam install --yes cppo ctypes ctypes-foreign dune zarith
  - bash .ci/script.sh
