/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: /Users/bhargava/Desktop/repositories/kremlin/krml -funroll-loops 8 -warn-error +9 -I /Users/bhargava/Desktop/repositories/hacl-star/lib/ -I /Users/bhargava/Desktop/repositories/hacl-star/lib/fst -I /Users/bhargava/Desktop/repositories/kremlin/kremlib -I /Users/bhargava/Desktop/repositories/hacl-star/specs -I . -ccopt -march=native -fbuiltin-uint128 -drop FStar.UInt128 -fnocompound-literals -fc89-scope -fparentheses -fcurly-braces -tmpdir aes-only-c aes-only-c/out.krml -skip-compilation -minimal -add-include "kremlib.h" -bundle Hacl.AesNI=*
 * F* version: 4693f414
 * KreMLin version: 557abd04
 */


#ifndef __Hacl_AesNI_H
#define __Hacl_AesNI_H


#include "kremlib.h"

void Hacl_AesNI_aes128_key_expansion(uint8_t *key, uint8_t *keyex);

void Hacl_AesNI_aes128_encrypt_block(uint8_t *cipher, uint8_t *plain, uint8_t *keyex);

#define __Hacl_AesNI_H_DEFINED
#endif
