USER_TARGET=libk256.a
USER_CFLAGS=
USER_C_FILES=
ALL_C_FILES=Hacl_Bignum.c Hacl_EC_K256.c Hacl_Hash.c Hacl_K256_ECDSA.c Hacl_Test_K256.c
ALL_H_FILES=Hacl_Bignum_Base.h Hacl_Bignum_K256.h Hacl_EC_K256.h Hacl_Hash.h Hacl_K256_ECDSA.h Hacl_Krmllib.h Hacl_Spec.h Hacl_Test_K256.h Lib_PrintBuffer.h internal/Hacl_Bignum.h internal/Hacl_K256_ECDSA.h internal/Hacl_Krmllib.h internal/Hacl_Lib.h
