
all:
	$(FSTAR_HOME)/bin/fstar.exe --include .. --include ../lib ../lib/Spec.Lib.IntSeq.fst ../Spec.Chacha20.fst Spec.Chacha20.Test.fst
	$(FSTAR_HOME)/bin/fstar.exe --include .. --include ../lib ../lib/Spec.Lib.IntSeq.fst ../Spec.Poly1305.fst Spec.Poly1305.Test.fst
