/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Addition_H
#define __Addition_H



#include "testlib.h"

typedef uint64_t *Addition_bignum;

bool
Addition_sub_loop_min(
  uint32_t bLen,
  uint64_t *a,
  uint64_t *b,
  bool carry,
  uint32_t count1,
  uint64_t *res
);

uint32_t
Addition_sub_loop_dif(uint32_t aLen, uint64_t *a, uint32_t ind, uint32_t dif, uint64_t *res);

void Addition_sub(uint32_t aLen, uint32_t bLen, uint64_t *a, uint64_t *b, uint64_t *res);
#endif
