/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Comparison_H
#define __Comparison_H


#include "Addition.h"
#include "testlib.h"

typedef uint64_t *Comparison_bignum;

bool Comparison_isMore_loop(uint64_t *a, uint64_t *b, uint32_t count1);

bool Comparison_isMore(uint32_t aLen, uint32_t bLen, uint64_t *a, uint64_t *b);
#endif
