/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Convert_H
#define __Convert_H


#include "Addition.h"
#include "Comparison.h"
#include "testlib.h"

typedef uint8_t *Convert_uint8_p;

typedef uint64_t *Convert_bignum;

extern uint32_t Convert_bn_bytes;

uint32_t Convert_get_size_nat(uint32_t lenText);

uint32_t Convert_bits_to_bn(uint32_t bits);

uint32_t Convert_bits_to_text(uint32_t bits);

void
Convert_text_to_nat_loop(
  uint8_t *input,
  uint32_t len,
  uint64_t *res,
  uint32_t num_words,
  uint32_t m,
  uint64_t word,
  uint32_t i
);

void Convert_text_to_nat(uint8_t *input, uint32_t len, uint64_t *res);

void Convert_nat_to_text_loop(uint64_t *input, uint8_t *res, uint32_t i, uint32_t j);

void Convert_nat_to_text(uint64_t *input, uint32_t len, uint8_t *res);
#endif
