/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Exponentiation_H
#define __Exponentiation_H


#include "Addition.h"
#include "Comparison.h"
#include "Convert.h"
#include "Shift.h"
#include "Division.h"
#include "Multiplication.h"
#include "testlib.h"

typedef uint64_t *Exponentiation_bignum;

extern uint32_t Exponentiation_bn_bits2;

bool Exponentiation_bn_bit_is_set(uint64_t *input, uint32_t ind);

void
Exponentiation_mod_exp_loop(
  uint32_t modBits,
  uint32_t aLen,
  uint32_t bBits,
  uint32_t resLen,
  uint64_t *n1,
  uint64_t *tmpV,
  uint64_t *b,
  uint64_t *res,
  uint32_t count1
);

void
Exponentiation_mod_exp(
  uint32_t modBits,
  uint32_t aLen,
  uint32_t bBits,
  uint32_t resLen,
  uint64_t *n1,
  uint64_t *a,
  uint64_t *b,
  uint64_t *res
);
#endif
