/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_Hash_Lib_Create_H
#define __Hacl_Hash_Lib_Create_H


#include "Addition.h"
#include "Comparison.h"
#include "Convert.h"
#include "Shift.h"
#include "Division.h"
#include "Multiplication.h"
#include "Exponentiation.h"
#include "testlib.h"

typedef uint8_t Hacl_Hash_Lib_Create_uint8_t;

typedef uint32_t Hacl_Hash_Lib_Create_uint32_t;

typedef uint64_t Hacl_Hash_Lib_Create_uint64_t;

typedef uint8_t Hacl_Hash_Lib_Create_uint8_ht;

typedef uint32_t Hacl_Hash_Lib_Create_uint32_ht;

typedef uint64_t Hacl_Hash_Lib_Create_uint64_ht;

typedef uint8_t *Hacl_Hash_Lib_Create_uint8_p;

typedef uint32_t *Hacl_Hash_Lib_Create_uint32_p;

typedef uint64_t *Hacl_Hash_Lib_Create_uint64_p;

uint8_t Hacl_Hash_Lib_Create_u8_to_s8(uint8_t a);

uint32_t Hacl_Hash_Lib_Create_u32_to_s32(uint32_t a);

uint64_t Hacl_Hash_Lib_Create_u32_to_s64(uint32_t a);

uint8_t Hacl_Hash_Lib_Create_s32_to_s8(uint32_t a);

uint64_t Hacl_Hash_Lib_Create_s32_to_s64(uint32_t a);

uint64_t Hacl_Hash_Lib_Create_u64_to_s64(uint64_t a);

void
Hacl_Hash_Lib_Create_hupd_4(uint32_t *buf, uint32_t v0, uint32_t v1, uint32_t v2, uint32_t v3);

void
Hacl_Hash_Lib_Create_hupd_8(
  uint32_t *buf,
  uint32_t v0,
  uint32_t v1,
  uint32_t v2,
  uint32_t v3,
  uint32_t v4,
  uint32_t v5,
  uint32_t v6,
  uint32_t v7
);

void
Hacl_Hash_Lib_Create_hupd_16(
  uint32_t *buf,
  uint32_t v0,
  uint32_t v1,
  uint32_t v2,
  uint32_t v3,
  uint32_t v4,
  uint32_t v5,
  uint32_t v6,
  uint32_t v7,
  uint32_t v8,
  uint32_t v9,
  uint32_t v10,
  uint32_t v11,
  uint32_t v12,
  uint32_t v13,
  uint32_t v14,
  uint32_t v15
);

void
Hacl_Hash_Lib_Create_hupd_64(
  uint32_t *buf,
  uint32_t v0,
  uint32_t v1,
  uint32_t v2,
  uint32_t v3,
  uint32_t v4,
  uint32_t v5,
  uint32_t v6,
  uint32_t v7,
  uint32_t v8,
  uint32_t v9,
  uint32_t v10,
  uint32_t v11,
  uint32_t v12,
  uint32_t v13,
  uint32_t v14,
  uint32_t v15,
  uint32_t v16,
  uint32_t v17,
  uint32_t v18,
  uint32_t v19,
  uint32_t v20,
  uint32_t v21,
  uint32_t v22,
  uint32_t v23,
  uint32_t v24,
  uint32_t v25,
  uint32_t v26,
  uint32_t v27,
  uint32_t v28,
  uint32_t v29,
  uint32_t v30,
  uint32_t v31,
  uint32_t v32,
  uint32_t v33,
  uint32_t v34,
  uint32_t v35,
  uint32_t v36,
  uint32_t v37,
  uint32_t v38,
  uint32_t v39,
  uint32_t v40,
  uint32_t v41,
  uint32_t v42,
  uint32_t v43,
  uint32_t v44,
  uint32_t v45,
  uint32_t v46,
  uint32_t v47,
  uint32_t v48,
  uint32_t v49,
  uint32_t v50,
  uint32_t v51,
  uint32_t v52,
  uint32_t v53,
  uint32_t v54,
  uint32_t v55,
  uint32_t v56,
  uint32_t v57,
  uint32_t v58,
  uint32_t v59,
  uint32_t v60,
  uint32_t v61,
  uint32_t v62,
  uint32_t v63
);

void
Hacl_Hash_Lib_Create_hupd64_4(
  uint64_t *buf,
  uint64_t v0,
  uint64_t v1,
  uint64_t v2,
  uint64_t v3
);

void
Hacl_Hash_Lib_Create_hupd64_8(
  uint64_t *buf,
  uint64_t v0,
  uint64_t v1,
  uint64_t v2,
  uint64_t v3,
  uint64_t v4,
  uint64_t v5,
  uint64_t v6,
  uint64_t v7
);

void
Hacl_Hash_Lib_Create_hupd64_16(
  uint64_t *buf,
  uint64_t v0,
  uint64_t v1,
  uint64_t v2,
  uint64_t v3,
  uint64_t v4,
  uint64_t v5,
  uint64_t v6,
  uint64_t v7,
  uint64_t v8,
  uint64_t v9,
  uint64_t v10,
  uint64_t v11,
  uint64_t v12,
  uint64_t v13,
  uint64_t v14,
  uint64_t v15
);

void
Hacl_Hash_Lib_Create_hupd64_80(
  uint64_t *buf,
  uint64_t v0,
  uint64_t v1,
  uint64_t v2,
  uint64_t v3,
  uint64_t v4,
  uint64_t v5,
  uint64_t v6,
  uint64_t v7,
  uint64_t v8,
  uint64_t v9,
  uint64_t v10,
  uint64_t v11,
  uint64_t v12,
  uint64_t v13,
  uint64_t v14,
  uint64_t v15,
  uint64_t v16,
  uint64_t v17,
  uint64_t v18,
  uint64_t v19,
  uint64_t v20,
  uint64_t v21,
  uint64_t v22,
  uint64_t v23,
  uint64_t v24,
  uint64_t v25,
  uint64_t v26,
  uint64_t v27,
  uint64_t v28,
  uint64_t v29,
  uint64_t v30,
  uint64_t v31,
  uint64_t v32,
  uint64_t v33,
  uint64_t v34,
  uint64_t v35,
  uint64_t v36,
  uint64_t v37,
  uint64_t v38,
  uint64_t v39,
  uint64_t v40,
  uint64_t v41,
  uint64_t v42,
  uint64_t v43,
  uint64_t v44,
  uint64_t v45,
  uint64_t v46,
  uint64_t v47,
  uint64_t v48,
  uint64_t v49,
  uint64_t v50,
  uint64_t v51,
  uint64_t v52,
  uint64_t v53,
  uint64_t v54,
  uint64_t v55,
  uint64_t v56,
  uint64_t v57,
  uint64_t v58,
  uint64_t v59,
  uint64_t v60,
  uint64_t v61,
  uint64_t v62,
  uint64_t v63,
  uint64_t v64,
  uint64_t v65,
  uint64_t v66,
  uint64_t v67,
  uint64_t v68,
  uint64_t v69,
  uint64_t v70,
  uint64_t v71,
  uint64_t v72,
  uint64_t v73,
  uint64_t v74,
  uint64_t v75,
  uint64_t v76,
  uint64_t v77,
  uint64_t v78,
  uint64_t v79
);
#endif
