/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Shift_H
#define __Shift_H


#include "Addition.h"
#include "Comparison.h"
#include "Convert.h"
#include "testlib.h"

typedef uint64_t *Shift_bignum;

extern uint32_t Shift_bn_bits2;

extern uint64_t Shift_bn_tbit;

extern uint64_t Shift_bn_mask2;

void Shift_lshift_loop(uint64_t *a, uint32_t count1, uint32_t nw, uint32_t lb, uint64_t *res);

void Shift_lshift(uint32_t aLen, uint64_t *a, uint32_t nCount, uint64_t *res);

void Shift_rshift1_loop(uint64_t *a, uint64_t carry, uint32_t ind, uint64_t *res);

void Shift_rshift1(uint32_t aLen, uint64_t *a, uint64_t *res);
#endif
