/* This file was auto-generated by KreMLin! */
#ifndef __Combinators_H
#define __Combinators_H



#include "kremlib.h"
#include "testlib.h"

void Combinators_for2(uint32_t start, uint32_t finish, void *inv, void (*f)(uint32_t x0));
#endif
