/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_Policies_H
#define __Hacl_Policies_H


#include "FStar.h"


uint8_t Hacl_Policies_declassify_u8(uint8_t x);

uint32_t Hacl_Policies_declassify_u32(uint32_t x);

uint64_t Hacl_Policies_declassify_u64(uint64_t x);

void Hacl_Policies_declassify_u128(FStar_UInt128_uint128 *x, FStar_UInt128_uint128 *ret);

uint8_t Hacl_Policies_leak_byte(uint8_t *b, uint32_t n1);

uint8_t Hacl_Policies_cmp_bytes_(uint8_t *b1, uint8_t *b2, uint32_t len, uint8_t tmp);

uint8_t Hacl_Policies_cmp_bytes(uint8_t *b1, uint8_t *b2, uint32_t len);
#endif
