module Hacl.Test.Trusted.Random.Hardware

open FStar.HyperStack.All
open FStar.Buffer
open FStar.UInt32

module Random = Hacl.Trusted.Random.Hardware

(* Base types *)
let uint32_t = FStar.Int32.t

(* Entry point *)
val main: unit -> Stack C.exit_code
  (requires (fun h -> True))
  (ensures  (fun h0 r h1 -> True))

let main () =
  push_frame();

  (* Allocate space to get randomness from the CPU *)
  let size = 64ul in
  let result = create 0uy size in

  (* Call the Random Number Generator *)
  Random.random_bytes result size;

  (* Generate and display some randomly generated bytes *)
  C.String.print (C.String.of_literal "Randomly generated bytes: \n");
  C.print_bytes result size;

  pop_frame();
  C.EXIT_SUCCESS
