/* This file auto-generated by KreMLin! */
#ifndef __Hacl_Symmetric_Chacha20_H
#define __Hacl_Symmetric_Chacha20_H
#include "HSalsa20.h"
#include "kremlib.h"
#include "testlib.h"

typedef uint32_t *Hacl_Symmetric_Chacha20_chacha_ctx;

void Hacl_Symmetric_Chacha20_chacha_keysetup(uint32_t *ctx, uint8_t *k);

void Hacl_Symmetric_Chacha20_chacha_ietf_ivsetup(uint32_t *ctx, uint8_t *iv, uint32_t counter);

void
Hacl_Symmetric_Chacha20_chacha_encrypt_bytes(
  uint32_t *ctx,
  uint8_t *m,
  uint8_t *c,
  uint32_t len
);
#endif
