/* This file auto-generated by KreMLin! */
#ifndef __Hacl_Symmetric_Salsa20_H
#define __Hacl_Symmetric_Salsa20_H


#include "Hacl_Symmetric_HSalsa20.h"
#include "Hacl_Symmetric_Chacha20.h"
#include "kremlib.h"
#include "testlib.h"

typedef uint32_t Hacl_Symmetric_Salsa20_h32;

typedef uint32_t Hacl_Symmetric_Salsa20_u32;

typedef uint8_t *Hacl_Symmetric_Salsa20_uint8_p;

uint32_t Hacl_Symmetric_Salsa20_rotate(uint32_t a, uint32_t s);

uint32_t Hacl_Symmetric_Salsa20_load32_le(uint8_t *k);

void Hacl_Symmetric_Salsa20_store32_le(uint8_t *k, uint32_t x);

void Hacl_Symmetric_Salsa20_crypto_core_salsa20(uint8_t *output, uint8_t *input, uint8_t *key);

void Hacl_Symmetric_Salsa20_xor_(uint8_t *c, uint8_t *m, uint8_t *block);

void
Hacl_Symmetric_Salsa20_lemma_modifies_3(
  uint8_t *c,
  uint8_t *input,
  uint8_t *block,
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2
);

void
Hacl_Symmetric_Salsa20_lemma_modifies_3_(
  uint8_t *c,
  uint8_t *input,
  uint8_t *block,
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2
);

uint64_t
Hacl_Symmetric_Salsa20_crypto_stream_salsa20_xor_ic_loop(
  uint8_t *c,
  uint8_t *m,
  uint8_t *block,
  uint8_t *input,
  uint8_t *kcopy,
  uint64_t mlen
);

void Hacl_Symmetric_Salsa20_xor_bytes(uint8_t *x, uint8_t *y, uint8_t *z, uint32_t len);

uint32_t Hacl_Symmetric_Salsa20_mod_64(uint64_t mlen);

void
Hacl_Symmetric_Salsa20_lemma_modifies_3_1(
  uint8_t *c,
  uint8_t *input,
  uint8_t *block,
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2,
  FStar_HyperStack_mem h3
);

void
Hacl_Symmetric_Salsa20_crypto_stream_salsa20_xor_ic__(
  uint8_t *n,
  uint64_t ic,
  uint8_t *k,
  uint8_t *local_state
);

void
Hacl_Symmetric_Salsa20_crypto_stream_salsa20_xor_ic_(
  uint8_t *c,
  uint8_t *m,
  uint64_t mlen,
  uint8_t *n,
  uint64_t ic,
  uint8_t *k
);

void
Hacl_Symmetric_Salsa20_crypto_stream_salsa20_xor_ic(
  uint8_t *c,
  uint8_t *m,
  uint64_t mlen,
  uint8_t *n,
  uint64_t ic,
  uint8_t *k
);

uint64_t
Hacl_Symmetric_Salsa20_crypto_stream_salsa20_loop(
  uint8_t *c,
  uint64_t clen,
  uint8_t *n,
  uint8_t *k,
  uint8_t *input
);

void
Hacl_Symmetric_Salsa20_lemma_modifies_4(
  uint8_t *c,
  uint8_t *input,
  uint8_t *block,
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2,
  FStar_HyperStack_mem h3
);

void
Hacl_Symmetric_Salsa20_crypto_stream_salsa20_(uint8_t *n, uint8_t *k, uint8_t *local_state);

void
Hacl_Symmetric_Salsa20_crypto_stream_salsa20(uint8_t *c, uint64_t clen, uint8_t *n, uint8_t *k);

void
Hacl_Symmetric_Salsa20_crypto_stream_salsa20_xor(
  uint8_t *c,
  uint8_t *m,
  uint64_t mlen,
  uint8_t *n,
  uint8_t *k
);
#endif
