/* This file auto-generated by KreMLin! */
#ifndef __Hacl_Symmetric_XSalsa20_H
#define __Hacl_Symmetric_XSalsa20_H


#include "Hacl_Symmetric_HSalsa20.h"
#include "Hacl_Symmetric_Chacha20.h"
#include "Hacl_Symmetric_Salsa20.h"
#include "kremlib.h"
#include "testlib.h"

typedef uint32_t Hacl_Symmetric_XSalsa20_h32;

typedef uint32_t Hacl_Symmetric_XSalsa20_u32;

typedef uint8_t *Hacl_Symmetric_XSalsa20_uint8_p;

void
Hacl_Symmetric_XSalsa20_crypto_stream_xsalsa20(
  uint8_t *c,
  uint64_t clen,
  uint8_t *n,
  uint8_t *k
);

void
Hacl_Symmetric_XSalsa20_crypto_stream_xsalsa20_xor_ic(
  uint8_t *c,
  uint8_t *m,
  uint64_t mlen,
  uint8_t *n,
  uint64_t ic,
  uint8_t *k
);

void
Hacl_Symmetric_XSalsa20_crypto_stream_xsalsa20_xor(
  uint8_t *c,
  uint8_t *m,
  uint64_t mlen,
  uint8_t *n,
  uint8_t *k
);
#endif
