#ifndef TWEETNACL_H
#define TWEETNACL_H
#define tweet_crypto_auth_PRIMITIVE "hmacsha512256"
#define tweet_crypto_auth tweet_crypto_auth_hmacsha512256
#define tweet_crypto_auth_verify tweet_crypto_auth_hmacsha512256_verify
#define tweet_crypto_auth_BYTES tweet_crypto_auth_hmacsha512256_BYTES
#define tweet_crypto_auth_KEYBYTES tweet_crypto_auth_hmacsha512256_KEYBYTES
#define tweet_crypto_auth_IMPLEMENTATION tweet_crypto_auth_hmacsha512256_IMPLEMENTATION
#define tweet_crypto_auth_VERSION tweet_crypto_auth_hmacsha512256_VERSION
#define tweet_crypto_auth_hmacsha512256_tweet_BYTES 32
#define tweet_crypto_auth_hmacsha512256_tweet_KEYBYTES 32
extern int tweet_crypto_auth_hmacsha512256_tweet(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *);
extern int tweet_crypto_auth_hmacsha512256_tweet_verify(const unsigned char *,const unsigned char *,unsigned long long,const unsigned char *);
#define tweet_crypto_auth_hmacsha512256_tweet_VERSION "-"
#define tweet_crypto_auth_hmacsha512256 tweet_crypto_auth_hmacsha512256_tweet
#define tweet_crypto_auth_hmacsha512256_verify tweet_crypto_auth_hmacsha512256_tweet_verify
#define tweet_crypto_auth_hmacsha512256_BYTES tweet_crypto_auth_hmacsha512256_tweet_BYTES
#define tweet_crypto_auth_hmacsha512256_KEYBYTES tweet_crypto_auth_hmacsha512256_tweet_KEYBYTES
#define tweet_crypto_auth_hmacsha512256_VERSION tweet_crypto_auth_hmacsha512256_tweet_VERSION
#define tweet_crypto_auth_hmacsha512256_IMPLEMENTATION "tweet_crypto_auth/hmacsha512256/tweet"
#define tweet_crypto_box_PRIMITIVE "curve25519xsalsa20poly1305"
#define tweet_crypto_box_open tweet_crypto_box_curve25519xsalsa20poly1305_open
#define tweet_crypto_box_keypair tweet_crypto_box_curve25519xsalsa20poly1305_keypair
#define tweet_crypto_box_beforenm tweet_crypto_box_curve25519xsalsa20poly1305_beforenm
#define tweet_crypto_box_afternm tweet_crypto_box_curve25519xsalsa20poly1305_afternm
#define tweet_crypto_box_open_afternm tweet_crypto_box_curve25519xsalsa20poly1305_open_afternm
#define tweet_crypto_box_PUBLICKEYBYTES tweet_crypto_box_curve25519xsalsa20poly1305_PUBLICKEYBYTES
#define tweet_crypto_box_SECRETKEYBYTES tweet_crypto_box_curve25519xsalsa20poly1305_SECRETKEYBYTES
#define tweet_crypto_box_BEFORENMBYTES tweet_crypto_box_curve25519xsalsa20poly1305_BEFORENMBYTES
#define tweet_crypto_box_NONCEBYTES tweet_crypto_box_curve25519xsalsa20poly1305_NONCEBYTES
#define tweet_crypto_box_ZEROBYTES tweet_crypto_box_curve25519xsalsa20poly1305_ZEROBYTES
#define tweet_crypto_box_BOXZEROBYTES tweet_crypto_box_curve25519xsalsa20poly1305_BOXZEROBYTES
#define tweet_crypto_box_IMPLEMENTATION tweet_crypto_box_curve25519xsalsa20poly1305_IMPLEMENTATION
#define tweet_crypto_box_VERSION tweet_crypto_box_curve25519xsalsa20poly1305_VERSION
#define tweet_crypto_box_curve25519xsalsa20poly1305_tweet_PUBLICKEYBYTES 32
#define tweet_crypto_box_curve25519xsalsa20poly1305_tweet_SECRETKEYBYTES 32
#define tweet_crypto_box_curve25519xsalsa20poly1305_tweet_BEFORENMBYTES 32
#define tweet_crypto_box_curve25519xsalsa20poly1305_tweet_NONCEBYTES 24
#define tweet_crypto_box_curve25519xsalsa20poly1305_tweet_ZEROBYTES 32
#define tweet_crypto_box_curve25519xsalsa20poly1305_tweet_BOXZEROBYTES 16

extern int tweet_crypto_box(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_crypto_box_curve25519xsalsa20poly1305_tweet(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_crypto_box_curve25519xsalsa20poly1305_tweet_open(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_crypto_box_curve25519xsalsa20poly1305_tweet_keypair(unsigned char *,unsigned char *);
extern int tweet_crypto_box_curve25519xsalsa20poly1305_tweet_beforenm(unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_crypto_box_curve25519xsalsa20poly1305_tweet_afternm(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
extern int tweet_crypto_box_curve25519xsalsa20poly1305_tweet_open_afternm(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
#define tweet_crypto_box_curve25519xsalsa20poly1305_tweet_VERSION "-"
#define tweet_crypto_box_curve25519xsalsa20poly1305 tweet_crypto_box_curve25519xsalsa20poly1305_tweet
#define tweet_crypto_box_curve25519xsalsa20poly1305_open tweet_crypto_box_curve25519xsalsa20poly1305_tweet_open
#define tweet_crypto_box_curve25519xsalsa20poly1305_keypair tweet_crypto_box_curve25519xsalsa20poly1305_tweet_keypair
#define tweet_crypto_box_curve25519xsalsa20poly1305_beforenm tweet_crypto_box_curve25519xsalsa20poly1305_tweet_beforenm
#define tweet_crypto_box_curve25519xsalsa20poly1305_afternm tweet_crypto_box_curve25519xsalsa20poly1305_tweet_afternm
#define tweet_crypto_box_curve25519xsalsa20poly1305_open_afternm tweet_crypto_box_curve25519xsalsa20poly1305_tweet_open_afternm
#define tweet_crypto_box_curve25519xsalsa20poly1305_PUBLICKEYBYTES tweet_crypto_box_curve25519xsalsa20poly1305_tweet_PUBLICKEYBYTES
#define tweet_crypto_box_curve25519xsalsa20poly1305_SECRETKEYBYTES tweet_crypto_box_curve25519xsalsa20poly1305_tweet_SECRETKEYBYTES
#define tweet_crypto_box_curve25519xsalsa20poly1305_BEFORENMBYTES tweet_crypto_box_curve25519xsalsa20poly1305_tweet_BEFORENMBYTES
#define tweet_crypto_box_curve25519xsalsa20poly1305_NONCEBYTES tweet_crypto_box_curve25519xsalsa20poly1305_tweet_NONCEBYTES
#define tweet_crypto_box_curve25519xsalsa20poly1305_ZEROBYTES tweet_crypto_box_curve25519xsalsa20poly1305_tweet_ZEROBYTES
#define tweet_crypto_box_curve25519xsalsa20poly1305_BOXZEROBYTES tweet_crypto_box_curve25519xsalsa20poly1305_tweet_BOXZEROBYTES
#define tweet_crypto_box_curve25519xsalsa20poly1305_VERSION tweet_crypto_box_curve25519xsalsa20poly1305_tweet_VERSION
#define tweet_crypto_box_curve25519xsalsa20poly1305_IMPLEMENTATION "tweet_crypto_box/curve25519xsalsa20poly1305/tweet"
#define tweet_crypto_core_PRIMITIVE "salsa20"
#define tweet_crypto_core tweet_crypto_core_salsa20
#define tweet_crypto_core_OUTPUTBYTES tweet_crypto_core_salsa20_OUTPUTBYTES
#define tweet_crypto_core_INPUTBYTES tweet_crypto_core_salsa20_INPUTBYTES
#define tweet_crypto_core_KEYBYTES tweet_crypto_core_salsa20_KEYBYTES
#define tweet_crypto_core_CONSTBYTES tweet_crypto_core_salsa20_CONSTBYTES
#define tweet_crypto_core_IMPLEMENTATION tweet_crypto_core_salsa20_IMPLEMENTATION
#define tweet_crypto_core_VERSION tweet_crypto_core_salsa20_VERSION
#define tweet_crypto_core_salsa20_tweet_OUTPUTBYTES 64
#define tweet_crypto_core_salsa20_tweet_INPUTBYTES 16
#define tweet_crypto_core_salsa20_tweet_KEYBYTES 32
#define tweet_crypto_core_salsa20_tweet_CONSTBYTES 16
extern int tweet_crypto_core_salsa20_tweet(unsigned char *,const unsigned char *,const unsigned char *,const unsigned char *);
#define tweet_crypto_core_salsa20_tweet_VERSION "-"
#define tweet_crypto_core_salsa20 tweet_crypto_core_salsa20_tweet
#define tweet_crypto_core_salsa20_OUTPUTBYTES tweet_crypto_core_salsa20_tweet_OUTPUTBYTES
#define tweet_crypto_core_salsa20_INPUTBYTES tweet_crypto_core_salsa20_tweet_INPUTBYTES
#define tweet_crypto_core_salsa20_KEYBYTES tweet_crypto_core_salsa20_tweet_KEYBYTES
#define tweet_crypto_core_salsa20_CONSTBYTES tweet_crypto_core_salsa20_tweet_CONSTBYTES
#define tweet_crypto_core_salsa20_VERSION tweet_crypto_core_salsa20_tweet_VERSION
#define tweet_crypto_core_salsa20_IMPLEMENTATION "tweet_crypto_core/salsa20/tweet"
#define tweet_crypto_core_hsalsa20_tweet_OUTPUTBYTES 32
#define tweet_crypto_core_hsalsa20_tweet_INPUTBYTES 16
#define tweet_crypto_core_hsalsa20_tweet_KEYBYTES 32
#define tweet_crypto_core_hsalsa20_tweet_CONSTBYTES 16
extern int tweet_crypto_core_hsalsa20_tweet(unsigned char *,const unsigned char *,const unsigned char *,const unsigned char *);
#define tweet_crypto_core_hsalsa20_tweet_VERSION "-"
#define tweet_crypto_core_hsalsa20 tweet_crypto_core_hsalsa20_tweet
#define tweet_crypto_core_hsalsa20_OUTPUTBYTES tweet_crypto_core_hsalsa20_tweet_OUTPUTBYTES
#define tweet_crypto_core_hsalsa20_INPUTBYTES tweet_crypto_core_hsalsa20_tweet_INPUTBYTES
#define tweet_crypto_core_hsalsa20_KEYBYTES tweet_crypto_core_hsalsa20_tweet_KEYBYTES
#define tweet_crypto_core_hsalsa20_CONSTBYTES tweet_crypto_core_hsalsa20_tweet_CONSTBYTES
#define tweet_crypto_core_hsalsa20_VERSION tweet_crypto_core_hsalsa20_tweet_VERSION
#define tweet_crypto_core_hsalsa20_IMPLEMENTATION "tweet_crypto_core/hsalsa20/tweet"
#define tweet_crypto_hashblocks_PRIMITIVE "sha512"
#define tweet_crypto_hashblocks tweet_crypto_hashblocks_sha512
#define tweet_crypto_hashblocks_STATEBYTES tweet_crypto_hashblocks_sha512_STATEBYTES
#define tweet_crypto_hashblocks_BLOCKBYTES tweet_crypto_hashblocks_sha512_BLOCKBYTES
#define tweet_crypto_hashblocks_IMPLEMENTATION tweet_crypto_hashblocks_sha512_IMPLEMENTATION
#define tweet_crypto_hashblocks_VERSION tweet_crypto_hashblocks_sha512_VERSION
#define tweet_crypto_hashblocks_sha512_tweet_STATEBYTES 64
#define tweet_crypto_hashblocks_sha512_tweet_BLOCKBYTES 128
extern int tweet_crypto_hashblocks_sha512_tweet(unsigned char *,const unsigned char *,unsigned long long);
#define tweet_crypto_hashblocks_sha512_tweet_VERSION "-"
#define tweet_crypto_hashblocks_sha512 tweet_crypto_hashblocks_sha512_tweet
#define tweet_crypto_hashblocks_sha512_STATEBYTES tweet_crypto_hashblocks_sha512_tweet_STATEBYTES
#define tweet_crypto_hashblocks_sha512_BLOCKBYTES tweet_crypto_hashblocks_sha512_tweet_BLOCKBYTES
#define tweet_crypto_hashblocks_sha512_VERSION tweet_crypto_hashblocks_sha512_tweet_VERSION
#define tweet_crypto_hashblocks_sha512_IMPLEMENTATION "tweet_crypto_hashblocks/sha512/tweet"
#define tweet_crypto_hashblocks_sha256_tweet_STATEBYTES 32
#define tweet_crypto_hashblocks_sha256_tweet_BLOCKBYTES 64
extern int tweet_crypto_hashblocks_sha256_tweet(unsigned char *,const unsigned char *,unsigned long long);
#define tweet_crypto_hashblocks_sha256_tweet_VERSION "-"
#define tweet_crypto_hashblocks_sha256 tweet_crypto_hashblocks_sha256_tweet
#define tweet_crypto_hashblocks_sha256_STATEBYTES tweet_crypto_hashblocks_sha256_tweet_STATEBYTES
#define tweet_crypto_hashblocks_sha256_BLOCKBYTES tweet_crypto_hashblocks_sha256_tweet_BLOCKBYTES
#define tweet_crypto_hashblocks_sha256_VERSION tweet_crypto_hashblocks_sha256_tweet_VERSION
#define tweet_crypto_hashblocks_sha256_IMPLEMENTATION "tweet_crypto_hashblocks/sha256/tweet"
#define tweet_crypto_hash_PRIMITIVE "sha512"
#define tweet_crypto_hash tweet_crypto_hash_sha512
#define tweet_crypto_hash_BYTES tweet_crypto_hash_sha512_BYTES
#define tweet_crypto_hash_IMPLEMENTATION tweet_crypto_hash_sha512_IMPLEMENTATION
#define tweet_crypto_hash_VERSION tweet_crypto_hash_sha512_VERSION
#define tweet_crypto_hash_sha512_tweet_BYTES 64
extern int tweet_crypto_hash_sha512_tweet(unsigned char *,const unsigned char *,unsigned long long);
#define tweet_crypto_hash_sha512_tweet_VERSION "-"
#define tweet_crypto_hash_sha512 tweet_crypto_hash_sha512_tweet
#define tweet_crypto_hash_sha512_BYTES tweet_crypto_hash_sha512_tweet_BYTES
#define tweet_crypto_hash_sha512_VERSION tweet_crypto_hash_sha512_tweet_VERSION
#define tweet_crypto_hash_sha512_IMPLEMENTATION "tweet_crypto_hash/sha512/tweet"
#define tweet_crypto_hash_sha256_tweet_BYTES 32
extern int tweet_crypto_hash_sha256_tweet(unsigned char *,const unsigned char *,unsigned long long);
#define tweet_crypto_hash_sha256_tweet_VERSION "-"
#define tweet_crypto_hash_sha256 tweet_crypto_hash_sha256_tweet
#define tweet_crypto_hash_sha256_BYTES tweet_crypto_hash_sha256_tweet_BYTES
#define tweet_crypto_hash_sha256_VERSION tweet_crypto_hash_sha256_tweet_VERSION
#define tweet_crypto_hash_sha256_IMPLEMENTATION "tweet_crypto_hash/sha256/tweet"
#define tweet_crypto_onetimeauth_PRIMITIVE "poly1305"
#define tweet_crypto_onetimeauth tweet_crypto_onetimeauth_poly1305
#define tweet_crypto_onetimeauth_verify tweet_crypto_onetimeauth_poly1305_verify
#define tweet_crypto_onetimeauth_BYTES tweet_crypto_onetimeauth_poly1305_BYTES
#define tweet_crypto_onetimeauth_KEYBYTES tweet_crypto_onetimeauth_poly1305_KEYBYTES
#define tweet_crypto_onetimeauth_IMPLEMENTATION tweet_crypto_onetimeauth_poly1305_IMPLEMENTATION
#define tweet_crypto_onetimeauth_VERSION tweet_crypto_onetimeauth_poly1305_VERSION
#define tweet_crypto_onetimeauth_poly1305_tweet_BYTES 16
#define tweet_crypto_onetimeauth_poly1305_tweet_KEYBYTES 32
extern int tweet_crypto_onetimeauth_poly1305_tweet(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *);
extern int tweet_crypto_onetimeauth_poly1305_tweet_verify(const unsigned char *,const unsigned char *,unsigned long long,const unsigned char *);
#define tweet_crypto_onetimeauth_poly1305_tweet_VERSION "-"
#define tweet_crypto_onetimeauth_poly1305 tweet_crypto_onetimeauth_poly1305_tweet
#define tweet_crypto_onetimeauth_poly1305_verify tweet_crypto_onetimeauth_poly1305_tweet_verify
#define tweet_crypto_onetimeauth_poly1305_BYTES tweet_crypto_onetimeauth_poly1305_tweet_BYTES
#define tweet_crypto_onetimeauth_poly1305_KEYBYTES tweet_crypto_onetimeauth_poly1305_tweet_KEYBYTES
#define tweet_crypto_onetimeauth_poly1305_VERSION tweet_crypto_onetimeauth_poly1305_tweet_VERSION
#define tweet_crypto_onetimeauth_poly1305_IMPLEMENTATION "tweet_crypto_onetimeauth/poly1305/tweet"
#define tweet_crypto_scalarmult_PRIMITIVE "curve25519"
#define tweet_crypto_scalarmult_base tweet_crypto_scalarmult_curve25519_base
#define tweet_crypto_scalarmult_BYTES tweet_crypto_scalarmult_curve25519_BYTES
#define tweet_crypto_scalarmult_SCALARBYTES tweet_crypto_scalarmult_curve25519_SCALARBYTES
#define tweet_crypto_scalarmult_IMPLEMENTATION tweet_crypto_scalarmult_curve25519_IMPLEMENTATION
#define tweet_crypto_scalarmult_VERSION tweet_crypto_scalarmult_curve25519_VERSION
#define tweet_crypto_scalarmult_curve25519_tweet_BYTES 32
#define tweet_crypto_scalarmult_curve25519_tweet_SCALARBYTES 32
extern int tweet_crypto_scalarmult(unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_crypto_scalarmult_curve25519(unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_crypto_scalarmult_curve25519_base(unsigned char *,const unsigned char *);
#define tweet_crypto_scalarmult_curve25519_tweet_VERSION "-"
#define tweet_crypto_scalarmult_curve25519 tweet_crypto_scalarmult_curve25519_tweet
#define tweet_crypto_scalarmult_curve25519_base tweet_crypto_scalarmult_curve25519_base
#define tweet_crypto_scalarmult_curve25519_BYTES tweet_crypto_scalarmult_curve25519_tweet_BYTES
#define tweet_crypto_scalarmult_curve25519_SCALARBYTES tweet_crypto_scalarmult_curve25519_tweet_SCALARBYTES
#define tweet_crypto_scalarmult_curve25519_VERSION tweet_crypto_scalarmult_curve25519_tweet_VERSION
#define tweet_crypto_scalarmult_curve25519_IMPLEMENTATION "tweet_crypto_scalarmult/curve25519/tweet"
#define tweet_crypto_secretbox_PRIMITIVE "xsalsa20poly1305"
#define tweet_crypto_secretbox tweet_crypto_secretbox_xsalsa20poly1305
#define tweet_crypto_secretbox_open tweet_crypto_secretbox_xsalsa20poly1305_open
#define tweet_crypto_secretbox_KEYBYTES tweet_crypto_secretbox_xsalsa20poly1305_KEYBYTES
#define tweet_crypto_secretbox_NONCEBYTES tweet_crypto_secretbox_xsalsa20poly1305_NONCEBYTES
#define tweet_crypto_secretbox_ZEROBYTES tweet_crypto_secretbox_xsalsa20poly1305_ZEROBYTES
#define tweet_crypto_secretbox_BOXZEROBYTES tweet_crypto_secretbox_xsalsa20poly1305_BOXZEROBYTES
#define tweet_crypto_secretbox_IMPLEMENTATION tweet_crypto_secretbox_xsalsa20poly1305_IMPLEMENTATION
#define tweet_crypto_secretbox_VERSION tweet_crypto_secretbox_xsalsa20poly1305_VERSION
#define tweet_crypto_secretbox_xsalsa20poly1305_tweet_KEYBYTES 32
#define tweet_crypto_secretbox_xsalsa20poly1305_tweet_NONCEBYTES 24
#define tweet_crypto_secretbox_xsalsa20poly1305_tweet_ZEROBYTES 32
#define tweet_crypto_secretbox_xsalsa20poly1305_tweet_BOXZEROBYTES 16
extern int tweet_crypto_secretbox_xsalsa20poly1305_tweet(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
extern int tweet_crypto_secretbox_xsalsa20poly1305_tweet_open(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
#define tweet_crypto_secretbox_xsalsa20poly1305_tweet_VERSION "-"
#define tweet_crypto_secretbox_xsalsa20poly1305 tweet_crypto_secretbox_xsalsa20poly1305_tweet
#define tweet_crypto_secretbox_xsalsa20poly1305_open tweet_crypto_secretbox_xsalsa20poly1305_tweet_open
#define tweet_crypto_secretbox_xsalsa20poly1305_KEYBYTES tweet_crypto_secretbox_xsalsa20poly1305_tweet_KEYBYTES
#define tweet_crypto_secretbox_xsalsa20poly1305_NONCEBYTES tweet_crypto_secretbox_xsalsa20poly1305_tweet_NONCEBYTES
#define tweet_crypto_secretbox_xsalsa20poly1305_ZEROBYTES tweet_crypto_secretbox_xsalsa20poly1305_tweet_ZEROBYTES
#define tweet_crypto_secretbox_xsalsa20poly1305_BOXZEROBYTES tweet_crypto_secretbox_xsalsa20poly1305_tweet_BOXZEROBYTES
#define tweet_crypto_secretbox_xsalsa20poly1305_VERSION tweet_crypto_secretbox_xsalsa20poly1305_tweet_VERSION
#define tweet_crypto_secretbox_xsalsa20poly1305_IMPLEMENTATION "tweet_crypto_secretbox/xsalsa20poly1305/tweet"
#define tweet_crypto_sign_PRIMITIVE "ed25519"
#define tweet_crypto_sign tweet_crypto_sign_ed25519
#define tweet_crypto_sign_open tweet_crypto_sign_ed25519_open
#define tweet_crypto_sign_keypair tweet_crypto_sign_ed25519_keypair
#define tweet_crypto_sign_BYTES tweet_crypto_sign_ed25519_BYTES
#define tweet_crypto_sign_PUBLICKEYBYTES tweet_crypto_sign_ed25519_PUBLICKEYBYTES
#define tweet_crypto_sign_SECRETKEYBYTES tweet_crypto_sign_ed25519_SECRETKEYBYTES
#define tweet_crypto_sign_IMPLEMENTATION tweet_crypto_sign_ed25519_IMPLEMENTATION
#define tweet_crypto_sign_VERSION tweet_crypto_sign_ed25519_VERSION
#define tweet_crypto_sign_ed25519_tweet_BYTES 64
#define tweet_crypto_sign_ed25519_tweet_PUBLICKEYBYTES 32
#define tweet_crypto_sign_ed25519_tweet_SECRETKEYBYTES 64
extern int tweet_crypto_sign_ed25519_tweet(unsigned char *,unsigned long long *,const unsigned char *,unsigned long long,const unsigned char *);
extern int tweet_crypto_sign_ed25519_tweet_open(unsigned char *,unsigned long long *,const unsigned char *,unsigned long long,const unsigned char *);
extern int tweet_crypto_sign_ed25519_tweet_keypair(unsigned char *,unsigned char *);
#define tweet_crypto_sign_ed25519_tweet_VERSION "-"
#define tweet_crypto_sign_ed25519 tweet_crypto_sign_ed25519_tweet
#define tweet_crypto_sign_ed25519_open tweet_crypto_sign_ed25519_tweet_open
#define tweet_crypto_sign_ed25519_keypair tweet_crypto_sign_ed25519_tweet_keypair
#define tweet_crypto_sign_ed25519_BYTES tweet_crypto_sign_ed25519_tweet_BYTES
#define tweet_crypto_sign_ed25519_PUBLICKEYBYTES tweet_crypto_sign_ed25519_tweet_PUBLICKEYBYTES
#define tweet_crypto_sign_ed25519_SECRETKEYBYTES tweet_crypto_sign_ed25519_tweet_SECRETKEYBYTES
#define tweet_crypto_sign_ed25519_VERSION tweet_crypto_sign_ed25519_tweet_VERSION
#define tweet_crypto_sign_ed25519_IMPLEMENTATION "tweet_crypto_sign/ed25519/tweet"
#define tweet_crypto_stream_PRIMITIVE "xsalsa20"
#define tweet_crypto_stream tweet_crypto_stream_xsalsa20
#define tweet_crypto_stream_xor tweet_crypto_stream_xsalsa20_xor
#define tweet_crypto_stream_KEYBYTES tweet_crypto_stream_xsalsa20_KEYBYTES
#define tweet_crypto_stream_NONCEBYTES tweet_crypto_stream_xsalsa20_NONCEBYTES
#define tweet_crypto_stream_IMPLEMENTATION tweet_crypto_stream_xsalsa20_IMPLEMENTATION
#define tweet_crypto_stream_VERSION tweet_crypto_stream_xsalsa20_VERSION
#define tweet_crypto_stream_xsalsa20_tweet_KEYBYTES 32
#define tweet_crypto_stream_xsalsa20_tweet_NONCEBYTES 24
extern int tweet_crypto_stream_xsalsa20_tweet(unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
extern int tweet_crypto_stream_xsalsa20_tweet_xor(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
#define tweet_crypto_stream_xsalsa20_tweet_VERSION "-"
#define tweet_crypto_stream_xsalsa20 tweet_crypto_stream_xsalsa20_tweet
#define tweet_crypto_stream_xsalsa20_xor tweet_crypto_stream_xsalsa20_tweet_xor
#define tweet_crypto_stream_xsalsa20_KEYBYTES tweet_crypto_stream_xsalsa20_tweet_KEYBYTES
#define tweet_crypto_stream_xsalsa20_NONCEBYTES tweet_crypto_stream_xsalsa20_tweet_NONCEBYTES
#define tweet_crypto_stream_xsalsa20_VERSION tweet_crypto_stream_xsalsa20_tweet_VERSION
#define tweet_crypto_stream_xsalsa20_IMPLEMENTATION "tweet_crypto_stream/xsalsa20/tweet"
#define tweet_crypto_stream_salsa20_tweet_KEYBYTES 32
#define tweet_crypto_stream_salsa20_tweet_NONCEBYTES 8
extern int tweet_crypto_stream_salsa20_tweet(unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
extern int tweet_crypto_stream_salsa20_tweet_xor(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
#define tweet_crypto_stream_salsa20_tweet_VERSION "-"
#define tweet_crypto_stream_salsa20 tweet_crypto_stream_salsa20_tweet
#define tweet_crypto_stream_salsa20_xor tweet_crypto_stream_salsa20_tweet_xor
#define tweet_crypto_stream_salsa20_KEYBYTES tweet_crypto_stream_salsa20_tweet_KEYBYTES
#define tweet_crypto_stream_salsa20_NONCEBYTES tweet_crypto_stream_salsa20_tweet_NONCEBYTES
#define tweet_crypto_stream_salsa20_VERSION tweet_crypto_stream_salsa20_tweet_VERSION
#define tweet_crypto_stream_salsa20_IMPLEMENTATION "tweet_crypto_stream/salsa20/tweet"
#define tweet_crypto_verify_PRIMITIVE "16"
#define tweet_crypto_verify tweet_crypto_verify_16
#define tweet_crypto_verify_BYTES tweet_crypto_verify_16_BYTES
#define tweet_crypto_verify_IMPLEMENTATION tweet_crypto_verify_16_IMPLEMENTATION
#define tweet_crypto_verify_VERSION tweet_crypto_verify_16_VERSION
#define tweet_crypto_verify_16_tweet_BYTES 16
extern int tweet_crypto_verify_16_tweet(const unsigned char *,const unsigned char *);
#define tweet_crypto_verify_16_tweet_VERSION "-"
#define tweet_crypto_verify_16 tweet_crypto_verify_16_tweet
#define tweet_crypto_verify_16_BYTES tweet_crypto_verify_16_tweet_BYTES
#define tweet_crypto_verify_16_VERSION tweet_crypto_verify_16_tweet_VERSION
#define tweet_crypto_verify_16_IMPLEMENTATION "tweet_crypto_verify/16/tweet"
#define tweet_crypto_verify_32_tweet_BYTES 32
extern int tweet_crypto_verify_32_tweet(const unsigned char *,const unsigned char *);
#define tweet_crypto_verify_32_tweet_VERSION "-"
#define tweet_crypto_verify_32 tweet_crypto_verify_32_tweet
#define tweet_crypto_verify_32_BYTES tweet_crypto_verify_32_tweet_BYTES
#define tweet_crypto_verify_32_VERSION tweet_crypto_verify_32_tweet_VERSION
#define tweet_crypto_verify_32_IMPLEMENTATION "tweet_crypto_verify/32/tweet"
#endif
