/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: /home/nkulatov/new/kremlin/krml -funroll-loops 8 -warn-error +9 -I /home/nkulatov/HaclAES/hacl-star/lib -I /home/nkulatov/new/kremlin/kremlib -I /home/nkulatov/HaclAES/hacl-star/specs -I . -I /home/nkulatov/HaclAES/hacl-star/code/experimental/aes -I /home/nkulatov/HaclAES/hacl-star/code/experimental/gf128 -ccopt -march=native -fbuiltin-uint128 -drop FStar.UInt128 -fnocompound-literals -fparentheses -fcurly-braces -tmpdir aesgcm-aes256-ni-c aesgcm-aes256-ni-c/out.krml -skip-compilation -minimal -add-include "kremlib.h" -add-include "vec128.h" -drop Lib.Vec128 -bundle Hacl.AES_256_GCM.NI=*
  F* version: f2134fe1
  KreMLin version: f534ac02
 */


#ifndef __Hacl_AES_256_GCM_NI_H
#define __Hacl_AES_256_GCM_NI_H


#include "kremlib.h"
#include "vec128.h"

typedef Lib_Vec128_vec128 *Hacl_AES_256_GCM_NI_aes_gcm_ctx;

void Hacl_AES_256_GCM_NI_aes256_gcm_init(Lib_Vec128_vec128 *ctx, uint8_t *key, uint8_t *nonce);

void
Hacl_AES_256_GCM_NI_aes256_gcm_encrypt(
  Lib_Vec128_vec128 *ctx,
  uint32_t len,
  uint8_t *out,
  uint8_t *text,
  uint32_t aad_len,
  uint8_t *aad
);

bool
Hacl_AES_256_GCM_NI_aes256_gcm_decrypt(
  Lib_Vec128_vec128 *ctx,
  uint32_t len,
  uint8_t *out,
  uint8_t *cipher,
  uint32_t aad_len,
  uint8_t *aad
);

#define __Hacl_AES_256_GCM_NI_H_DEFINED
#endif
