/* This file auto-generated by KreMLin! */
#ifndef __Hacl_EC_Curve25519_Bigint_H
#define __Hacl_EC_Curve25519_Bigint_H


#include "Prims.h"
#include "FStar_Mul.h"
#include "FStar_Squash.h"
#include "FStar_StrongExcludedMiddle.h"
#include "FStar_List_Tot.h"
#include "FStar_Classical.h"
#include "FStar_ListProperties.h"
#include "FStar_SeqProperties.h"
#include "FStar_Math_Lemmas.h"
#include "FStar_BitVector.h"
#include "FStar_UInt.h"
#include "FStar_Int.h"
#include "FStar_FunctionalExtensionality.h"
#include "FStar_PropositionalExtensionality.h"
#include "FStar_PredicateExtensionality.h"
#include "FStar_TSet.h"
#include "FStar_Set.h"
#include "FStar_Map.h"
#include "FStar_Ghost.h"
#include "FStar_All.h"
#include "Hacl_UInt64.h"
#include "Hacl_UInt128.h"
#include "Hacl_UInt32.h"
#include "Hacl_UInt8.h"
#include "Hacl_Cast.h"
#include "FStar_Buffer.h"
#include "FStar_Buffer_Quantifiers.h"
#include "Hacl_EC_Curve25519_Parameters.h"
#include "kremlib.h"

typedef uint8_t Hacl_EC_Curve25519_Bigint_u8;

typedef uint32_t Hacl_EC_Curve25519_Bigint_u32;

typedef uint64_t Hacl_EC_Curve25519_Bigint_u64;

typedef uint8_t Hacl_EC_Curve25519_Bigint_s8;

typedef uint64_t Hacl_EC_Curve25519_Bigint_s64;

typedef FStar_UInt128_t Hacl_EC_Curve25519_Bigint_s128;

typedef uint8_t *Hacl_EC_Curve25519_Bigint_u8s;

typedef uint64_t *Hacl_EC_Curve25519_Bigint_u64s;

typedef FStar_UInt128_t *Hacl_EC_Curve25519_Bigint_u128s;

typedef FStar_HyperStack_mem Hacl_EC_Curve25519_Bigint_heap;

typedef Prims_pos (*Hacl_EC_Curve25519_Bigint_template)(Prims_nat x0);

typedef Prims_pos (*Hacl_EC_Curve25519_Bigint_template_const)(Prims_nat x0);

Prims_pos Hacl_EC_Curve25519_Bigint_byte_templ(Prims_nat x);

typedef uint64_t *Hacl_EC_Curve25519_Bigint_bigint;

typedef FStar_UInt128_t *Hacl_EC_Curve25519_Bigint_bigint_wide;

typedef uint8_t *Hacl_EC_Curve25519_Bigint_bytes;

Prims_nat Hacl_EC_Curve25519_Bigint_bitweight(Prims_pos (*t)(Prims_nat x0), Prims_nat n);

void Hacl_EC_Curve25519_Bigint_bitweight_def(Prims_pos (*t)(Prims_nat x0), Prims_int n);

Prims_nat Hacl_EC_Curve25519_Bigint_eval(FStar_HyperStack_mem h, uint64_t *b, Prims_nat n);

Prims_nat
Hacl_EC_Curve25519_Bigint_eval_wide(FStar_HyperStack_mem h, FStar_UInt128_t *b, Prims_nat n);

void Hacl_EC_Curve25519_Bigint_eval_def(FStar_HyperStack_mem h, uint64_t *b, Prims_nat n);

void
Hacl_EC_Curve25519_Bigint_eval_wide_def(
  FStar_HyperStack_mem h,
  FStar_UInt128_t *b,
  Prims_nat n
);

Prims_nat
Hacl_EC_Curve25519_Bigint_eval_bytes(FStar_HyperStack_mem h, uint8_t *b, Prims_nat n);

Prims_nat Hacl_EC_Curve25519_Bigint_maxValue(FStar_HyperStack_mem h, uint64_t *b, Prims_pos l);

Prims_nat
Hacl_EC_Curve25519_Bigint_maxValue_wide(
  FStar_HyperStack_mem h,
  FStar_UInt128_t *b,
  Prims_pos l
);

void
Hacl_EC_Curve25519_Bigint_maxValue_lemma_aux(FStar_HyperStack_mem h, uint64_t *b, Prims_pos l);

void Hacl_EC_Curve25519_Bigint_maxValue_lemma(FStar_HyperStack_mem h, uint64_t *b);

void
Hacl_EC_Curve25519_Bigint_maxValue_bound_lemma_aux(
  FStar_HyperStack_mem h,
  uint64_t *b,
  Prims_pos l,
  Prims_nat bound
);

void
Hacl_EC_Curve25519_Bigint_maxValue_bound_lemma(
  FStar_HyperStack_mem h,
  uint64_t *b,
  Prims_nat bound
);

Prims_nat Hacl_EC_Curve25519_Bigint_maxValueNorm(FStar_HyperStack_mem h, uint64_t *b);

Prims_nat
Hacl_EC_Curve25519_Bigint_maxValueIdx(FStar_HyperStack_mem h, uint64_t *b, Prims_pos l);

void
Hacl_EC_Curve25519_Bigint_maxValue_eq_lemma(
  FStar_HyperStack_mem ha,
  FStar_HyperStack_mem hb,
  uint64_t *a,
  uint64_t *b,
  Prims_pos l
);

void
Hacl_EC_Curve25519_Bigint_maxValueNorm_eq_lemma(
  FStar_HyperStack_mem ha,
  FStar_HyperStack_mem hb,
  uint64_t *a,
  uint64_t *b
);

void
Hacl_EC_Curve25519_Bigint_maxValue_wide_lemma_aux(
  FStar_HyperStack_mem h,
  FStar_UInt128_t *b,
  Prims_pos l
);

void Hacl_EC_Curve25519_Bigint_maxValue_wide_lemma(FStar_HyperStack_mem h, FStar_UInt128_t *b);

void
Hacl_EC_Curve25519_Bigint_maxValue_wide_bound_lemma_aux(
  FStar_HyperStack_mem h,
  FStar_UInt128_t *b,
  Prims_pos l,
  Prims_nat bound
);

void
Hacl_EC_Curve25519_Bigint_maxValue_wide_bound_lemma(
  FStar_HyperStack_mem h,
  FStar_UInt128_t *b,
  Prims_nat bound
);

Prims_nat
Hacl_EC_Curve25519_Bigint_maxValueNorm_wide(FStar_HyperStack_mem h, FStar_UInt128_t *b);

Prims_nat
Hacl_EC_Curve25519_Bigint_maxValueIdx_wide(
  FStar_HyperStack_mem h,
  FStar_UInt128_t *b,
  Prims_pos l
);

void
Hacl_EC_Curve25519_Bigint_maxValue_wide_eq_lemma(
  FStar_HyperStack_mem ha,
  FStar_HyperStack_mem hb,
  FStar_UInt128_t *a,
  FStar_UInt128_t *b,
  Prims_pos l
);

void
Hacl_EC_Curve25519_Bigint_maxValueNorm_wide_eq_lemma(
  FStar_HyperStack_mem ha,
  FStar_HyperStack_mem hb,
  FStar_UInt128_t *a,
  FStar_UInt128_t *b
);

void
Hacl_EC_Curve25519_Bigint_eval_eq_lemma(
  FStar_HyperStack_mem ha,
  FStar_HyperStack_mem hb,
  uint64_t *a,
  uint64_t *b,
  Prims_nat len
);

void
Hacl_EC_Curve25519_Bigint_eval_partial_eq_lemma(
  FStar_HyperStack_mem ha,
  FStar_HyperStack_mem hb,
  uint64_t *a,
  uint64_t *b,
  Prims_nat ctr,
  Prims_nat len
);

void Hacl_EC_Curve25519_Bigint_eval_null(FStar_HyperStack_mem h, uint64_t *b, Prims_nat len);

void
Hacl_EC_Curve25519_Bigint_max_value_of_null_lemma(
  FStar_HyperStack_mem h,
  uint64_t *b,
  Prims_pos l
);
#endif
