/* This file auto-generated by KreMLin! */
#ifndef __Hacl_EC_Curve25519_Bignum_H
#define __Hacl_EC_Curve25519_Bignum_H


#include "Prims.h"
#include "FStar_Mul.h"
#include "FStar_Squash.h"
#include "FStar_StrongExcludedMiddle.h"
#include "FStar_List_Tot.h"
#include "FStar_Classical.h"
#include "FStar_ListProperties.h"
#include "FStar_SeqProperties.h"
#include "FStar_Math_Lemmas.h"
#include "FStar_BitVector.h"
#include "FStar_UInt.h"
#include "FStar_Int.h"
#include "FStar_FunctionalExtensionality.h"
#include "FStar_PropositionalExtensionality.h"
#include "FStar_PredicateExtensionality.h"
#include "FStar_TSet.h"
#include "FStar_Set.h"
#include "FStar_Map.h"
#include "FStar_Ghost.h"
#include "FStar_All.h"
#include "Hacl_UInt64.h"
#include "Hacl_UInt128.h"
#include "Hacl_UInt32.h"
#include "Hacl_UInt8.h"
#include "Hacl_Cast.h"
#include "FStar_Buffer.h"
#include "FStar_Buffer_Quantifiers.h"
#include "Hacl_EC_Curve25519_Parameters.h"
#include "Hacl_EC_Curve25519_Bigint.h"
#include "Hacl_EC_Curve25519_Utils.h"
#include "Hacl_EC_Curve25519_Bignum_Fproduct.h"
#include "Hacl_EC_Curve25519_Bignum_Fscalar.h"
#include "Hacl_EC_Curve25519_Bignum_Fdifference.h"
#include "Hacl_EC_Curve25519_Bignum_Fsum.h"
#include "Hacl_EC_Curve25519_Bignum_Modulo.h"
#include "kremlib.h"

void Hacl_EC_Curve25519_Bignum_copy_bigint(uint64_t *output, uint64_t *i);

void Hacl_EC_Curve25519_Bignum_copy_to_bigint_(uint64_t *output, FStar_UInt128_t *b);

void Hacl_EC_Curve25519_Bignum_copy_to_bigint(uint64_t *output, FStar_UInt128_t *b);

void Hacl_EC_Curve25519_Bignum_copy_to_bigint_wide_(FStar_UInt128_t *output, uint64_t *b);

void Hacl_EC_Curve25519_Bignum_copy_to_bigint_wide(FStar_UInt128_t *output, uint64_t *b);

void Hacl_EC_Curve25519_Bignum_modulo(uint64_t *output, FStar_UInt128_t *b);

void Hacl_EC_Curve25519_Bignum_fsum(uint64_t *a, uint64_t *b);

void Hacl_EC_Curve25519_Bignum_fdifference(uint64_t *a, uint64_t *b);

void Hacl_EC_Curve25519_Bignum_fscalar(uint64_t *res, uint64_t *b, uint64_t s);

void Hacl_EC_Curve25519_Bignum_fmul(uint64_t *res, uint64_t *a, uint64_t *b);

void Hacl_EC_Curve25519_Bignum_fsquare(uint64_t *res, uint64_t *a);
#endif
