/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: /Users/bhargava/Desktop/repositories/kremlin/krml -funroll-loops 8 -warn-error +9 -I /Users/bhargava/Desktop/repositories/hacl-star/lib/ -I /Users/bhargava/Desktop/repositories/hacl-star/lib/fst -I /Users/bhargava/Desktop/repositories/kremlin/kremlib -I /Users/bhargava/Desktop/repositories/hacl-star/specs -I . -ccopt -march=native -fbuiltin-uint128 -drop FStar.UInt128 -fnocompound-literals -fc89-scope -fparentheses -fcurly-braces -tmpdir aes-only-c aes-only-c/out.krml -skip-compilation -minimal -add-include "kremlib.h" -bundle Hacl.AesNI=*
 * F* version: 4693f414
 * KreMLin version: 557abd04
 */

#include "Hacl_AesNI.h"
#include "vec128.h"

void Hacl_AesNI_aes128_key_expansion(uint8_t *key, uint8_t *keyex)
{
  uint32_t klen1 = (uint32_t)1U;
  Lib_Vec128_vec128 *uu____0 = (Lib_Vec128_vec128 *)keyex;
  Lib_Vec128_vec128 *prev;
  Lib_Vec128_vec128 *next;
  Lib_Vec128_vec128 n00;
  Lib_Vec128_vec128 key10;
  Lib_Vec128_vec128 key20;
  Lib_Vec128_vec128 key30;
  Lib_Vec128_vec128 key40;
  Lib_Vec128_vec128 *prev1;
  Lib_Vec128_vec128 *next1;
  Lib_Vec128_vec128 n01;
  Lib_Vec128_vec128 key11;
  Lib_Vec128_vec128 key21;
  Lib_Vec128_vec128 key31;
  Lib_Vec128_vec128 key41;
  Lib_Vec128_vec128 *prev2;
  Lib_Vec128_vec128 *next2;
  Lib_Vec128_vec128 n02;
  Lib_Vec128_vec128 key12;
  Lib_Vec128_vec128 key22;
  Lib_Vec128_vec128 key32;
  Lib_Vec128_vec128 key42;
  Lib_Vec128_vec128 *prev3;
  Lib_Vec128_vec128 *next3;
  Lib_Vec128_vec128 n03;
  Lib_Vec128_vec128 key13;
  Lib_Vec128_vec128 key23;
  Lib_Vec128_vec128 key33;
  Lib_Vec128_vec128 key43;
  Lib_Vec128_vec128 *prev4;
  Lib_Vec128_vec128 *next4;
  Lib_Vec128_vec128 n04;
  Lib_Vec128_vec128 key14;
  Lib_Vec128_vec128 key24;
  Lib_Vec128_vec128 key34;
  Lib_Vec128_vec128 key44;
  Lib_Vec128_vec128 *prev5;
  Lib_Vec128_vec128 *next5;
  Lib_Vec128_vec128 n05;
  Lib_Vec128_vec128 key15;
  Lib_Vec128_vec128 key25;
  Lib_Vec128_vec128 key35;
  Lib_Vec128_vec128 key45;
  Lib_Vec128_vec128 *prev6;
  Lib_Vec128_vec128 *next6;
  Lib_Vec128_vec128 n06;
  Lib_Vec128_vec128 key16;
  Lib_Vec128_vec128 key26;
  Lib_Vec128_vec128 key36;
  Lib_Vec128_vec128 key46;
  Lib_Vec128_vec128 *prev7;
  Lib_Vec128_vec128 *next7;
  Lib_Vec128_vec128 n07;
  Lib_Vec128_vec128 key17;
  Lib_Vec128_vec128 key27;
  Lib_Vec128_vec128 key37;
  Lib_Vec128_vec128 key47;
  Lib_Vec128_vec128 *prev8;
  Lib_Vec128_vec128 *next8;
  Lib_Vec128_vec128 n08;
  Lib_Vec128_vec128 key18;
  Lib_Vec128_vec128 key28;
  Lib_Vec128_vec128 key38;
  Lib_Vec128_vec128 key48;
  Lib_Vec128_vec128 *prev9;
  Lib_Vec128_vec128 *next9;
  Lib_Vec128_vec128 n0;
  Lib_Vec128_vec128 key1;
  Lib_Vec128_vec128 key2;
  Lib_Vec128_vec128 key3;
  Lib_Vec128_vec128 key4;
  uu____0[0U] = Lib_Vec128_vec128_load_le(key);
  prev = (Lib_Vec128_vec128 *)keyex;
  next = (Lib_Vec128_vec128 *)keyex + klen1;
  next[0U] = Lib_Vec128_ni_aes_keygen_assist(prev[0U], (uint8_t)0x01U);
  n00 = next[0U];
  next[0U] =
    Lib_Vec128_vec128_shuffle32(n00,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key10 = prev[0U];
  key20 = Lib_Vec128_vec128_xor(key10, Lib_Vec128_vec128_shift_left(key10, (uint32_t)32U));
  key30 = Lib_Vec128_vec128_xor(key20, Lib_Vec128_vec128_shift_left(key20, (uint32_t)32U));
  key40 = Lib_Vec128_vec128_xor(key30, Lib_Vec128_vec128_shift_left(key30, (uint32_t)32U));
  next[0U] = Lib_Vec128_vec128_xor(next[0U], key40);
  prev1 = (Lib_Vec128_vec128 *)keyex + klen1;
  next1 = (Lib_Vec128_vec128 *)keyex + (uint32_t)2U * klen1;
  next1[0U] = Lib_Vec128_ni_aes_keygen_assist(prev1[0U], (uint8_t)0x02U);
  n01 = next1[0U];
  next1[0U] =
    Lib_Vec128_vec128_shuffle32(n01,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key11 = prev1[0U];
  key21 = Lib_Vec128_vec128_xor(key11, Lib_Vec128_vec128_shift_left(key11, (uint32_t)32U));
  key31 = Lib_Vec128_vec128_xor(key21, Lib_Vec128_vec128_shift_left(key21, (uint32_t)32U));
  key41 = Lib_Vec128_vec128_xor(key31, Lib_Vec128_vec128_shift_left(key31, (uint32_t)32U));
  next1[0U] = Lib_Vec128_vec128_xor(next1[0U], key41);
  prev2 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)2U;
  next2 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)3U;
  next2[0U] = Lib_Vec128_ni_aes_keygen_assist(prev2[0U], (uint8_t)0x04U);
  n02 = next2[0U];
  next2[0U] =
    Lib_Vec128_vec128_shuffle32(n02,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key12 = prev2[0U];
  key22 = Lib_Vec128_vec128_xor(key12, Lib_Vec128_vec128_shift_left(key12, (uint32_t)32U));
  key32 = Lib_Vec128_vec128_xor(key22, Lib_Vec128_vec128_shift_left(key22, (uint32_t)32U));
  key42 = Lib_Vec128_vec128_xor(key32, Lib_Vec128_vec128_shift_left(key32, (uint32_t)32U));
  next2[0U] = Lib_Vec128_vec128_xor(next2[0U], key42);
  prev3 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)3U;
  next3 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)4U;
  next3[0U] = Lib_Vec128_ni_aes_keygen_assist(prev3[0U], (uint8_t)0x08U);
  n03 = next3[0U];
  next3[0U] =
    Lib_Vec128_vec128_shuffle32(n03,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key13 = prev3[0U];
  key23 = Lib_Vec128_vec128_xor(key13, Lib_Vec128_vec128_shift_left(key13, (uint32_t)32U));
  key33 = Lib_Vec128_vec128_xor(key23, Lib_Vec128_vec128_shift_left(key23, (uint32_t)32U));
  key43 = Lib_Vec128_vec128_xor(key33, Lib_Vec128_vec128_shift_left(key33, (uint32_t)32U));
  next3[0U] = Lib_Vec128_vec128_xor(next3[0U], key43);
  prev4 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)4U;
  next4 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)5U;
  next4[0U] = Lib_Vec128_ni_aes_keygen_assist(prev4[0U], (uint8_t)0x10U);
  n04 = next4[0U];
  next4[0U] =
    Lib_Vec128_vec128_shuffle32(n04,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key14 = prev4[0U];
  key24 = Lib_Vec128_vec128_xor(key14, Lib_Vec128_vec128_shift_left(key14, (uint32_t)32U));
  key34 = Lib_Vec128_vec128_xor(key24, Lib_Vec128_vec128_shift_left(key24, (uint32_t)32U));
  key44 = Lib_Vec128_vec128_xor(key34, Lib_Vec128_vec128_shift_left(key34, (uint32_t)32U));
  next4[0U] = Lib_Vec128_vec128_xor(next4[0U], key44);
  prev5 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)5U;
  next5 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)6U;
  next5[0U] = Lib_Vec128_ni_aes_keygen_assist(prev5[0U], (uint8_t)0x20U);
  n05 = next5[0U];
  next5[0U] =
    Lib_Vec128_vec128_shuffle32(n05,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key15 = prev5[0U];
  key25 = Lib_Vec128_vec128_xor(key15, Lib_Vec128_vec128_shift_left(key15, (uint32_t)32U));
  key35 = Lib_Vec128_vec128_xor(key25, Lib_Vec128_vec128_shift_left(key25, (uint32_t)32U));
  key45 = Lib_Vec128_vec128_xor(key35, Lib_Vec128_vec128_shift_left(key35, (uint32_t)32U));
  next5[0U] = Lib_Vec128_vec128_xor(next5[0U], key45);
  prev6 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)6U;
  next6 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)7U;
  next6[0U] = Lib_Vec128_ni_aes_keygen_assist(prev6[0U], (uint8_t)0x40U);
  n06 = next6[0U];
  next6[0U] =
    Lib_Vec128_vec128_shuffle32(n06,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key16 = prev6[0U];
  key26 = Lib_Vec128_vec128_xor(key16, Lib_Vec128_vec128_shift_left(key16, (uint32_t)32U));
  key36 = Lib_Vec128_vec128_xor(key26, Lib_Vec128_vec128_shift_left(key26, (uint32_t)32U));
  key46 = Lib_Vec128_vec128_xor(key36, Lib_Vec128_vec128_shift_left(key36, (uint32_t)32U));
  next6[0U] = Lib_Vec128_vec128_xor(next6[0U], key46);
  prev7 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)7U;
  next7 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)8U;
  next7[0U] = Lib_Vec128_ni_aes_keygen_assist(prev7[0U], (uint8_t)0x80U);
  n07 = next7[0U];
  next7[0U] =
    Lib_Vec128_vec128_shuffle32(n07,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key17 = prev7[0U];
  key27 = Lib_Vec128_vec128_xor(key17, Lib_Vec128_vec128_shift_left(key17, (uint32_t)32U));
  key37 = Lib_Vec128_vec128_xor(key27, Lib_Vec128_vec128_shift_left(key27, (uint32_t)32U));
  key47 = Lib_Vec128_vec128_xor(key37, Lib_Vec128_vec128_shift_left(key37, (uint32_t)32U));
  next7[0U] = Lib_Vec128_vec128_xor(next7[0U], key47);
  prev8 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)8U;
  next8 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)9U;
  next8[0U] = Lib_Vec128_ni_aes_keygen_assist(prev8[0U], (uint8_t)0x1bU);
  n08 = next8[0U];
  next8[0U] =
    Lib_Vec128_vec128_shuffle32(n08,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key18 = prev8[0U];
  key28 = Lib_Vec128_vec128_xor(key18, Lib_Vec128_vec128_shift_left(key18, (uint32_t)32U));
  key38 = Lib_Vec128_vec128_xor(key28, Lib_Vec128_vec128_shift_left(key28, (uint32_t)32U));
  key48 = Lib_Vec128_vec128_xor(key38, Lib_Vec128_vec128_shift_left(key38, (uint32_t)32U));
  next8[0U] = Lib_Vec128_vec128_xor(next8[0U], key48);
  prev9 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)9U;
  next9 = (Lib_Vec128_vec128 *)keyex + klen1 * (uint32_t)10U;
  next9[0U] = Lib_Vec128_ni_aes_keygen_assist(prev9[0U], (uint8_t)0x36U);
  n0 = next9[0U];
  next9[0U] =
    Lib_Vec128_vec128_shuffle32(n0,
      Lib_Vec128_vec128_shuffle32_spec((uint8_t)3U, (uint8_t)3U, (uint8_t)3U, (uint8_t)3U));
  key1 = prev9[0U];
  key2 = Lib_Vec128_vec128_xor(key1, Lib_Vec128_vec128_shift_left(key1, (uint32_t)32U));
  key3 = Lib_Vec128_vec128_xor(key2, Lib_Vec128_vec128_shift_left(key2, (uint32_t)32U));
  key4 = Lib_Vec128_vec128_xor(key3, Lib_Vec128_vec128_shift_left(key3, (uint32_t)32U));
  next9[0U] = Lib_Vec128_vec128_xor(next9[0U], key4);
}

void Hacl_AesNI_aes128_encrypt_block(uint8_t *cipher, uint8_t *plain, uint8_t *keyex)
{
  KRML_CHECK_SIZE(sizeof (Lib_Vec128_vec128), (uint32_t)4U);
  {
    Lib_Vec128_vec128 st[4U];
    {
      uint32_t _i;
      for (_i = 0U; _i < (uint32_t)4U; ++_i)
        st[_i] = Lib_Vec128_vec128_zero;
    }
    {
      uint32_t klen1;
      Lib_Vec128_vec128 *k0;
      Lib_Vec128_vec128 *kr;
      Lib_Vec128_vec128 *kn;
      st[0U] = Lib_Vec128_vec128_load_le(plain);
      klen1 = (uint32_t)1U;
      k0 = (Lib_Vec128_vec128 *)keyex;
      kr = (Lib_Vec128_vec128 *)keyex + klen1;
      kn = (Lib_Vec128_vec128 *)keyex + (uint32_t)10U * klen1;
      st[0U] = Lib_Vec128_vec128_xor(st[0U], k0[0U]);
      st[1U] = Lib_Vec128_vec128_xor(st[1U], k0[0U]);
      st[2U] = Lib_Vec128_vec128_xor(st[2U], k0[0U]);
      st[3U] = Lib_Vec128_vec128_xor(st[3U], k0[0U]);
      {
        uint32_t i;
        for (i = (uint32_t)0U; i < (uint32_t)10U - (uint32_t)1U; i = i + (uint32_t)1U)
        {
          Lib_Vec128_vec128 *sub_key = kr + i * (uint32_t)1U;
          st[0U] = Lib_Vec128_ni_aes_enc(st[0U], sub_key[0U]);
          st[1U] = Lib_Vec128_ni_aes_enc(st[1U], sub_key[0U]);
          st[2U] = Lib_Vec128_ni_aes_enc(st[2U], sub_key[0U]);
          st[3U] = Lib_Vec128_ni_aes_enc(st[3U], sub_key[0U]);
        }
      }
      st[0U] = Lib_Vec128_ni_aes_enc_last(st[0U], kn[0U]);
      st[1U] = Lib_Vec128_ni_aes_enc_last(st[1U], kn[0U]);
      st[2U] = Lib_Vec128_ni_aes_enc_last(st[2U], kn[0U]);
      st[3U] = Lib_Vec128_ni_aes_enc_last(st[3U], kn[0U]);
      Lib_Vec128_vec128_store_le(cipher, st[0U]);
    }
  }
}

