clean:
	$(MAKE) -C 0-coding-field-arithmetic-in-fstar clean
	$(MAKE) -C 1-recursion-vs-loops clean
	$(MAKE) -C 2-verifying-memory-safety clean
	$(MAKE) -C 3-verifying-overflow-safety clean
	$(MAKE) -C 4-verifying-functional-correctness clean
