/* This file was auto-generated by KreMLin! */
#ifndef __Hacl_Utils_Experimental_H
#define __Hacl_Utils_Experimental_H



#include "kremlib.h"
#include "testlib.h"

typedef uint8_t Hacl_Utils_Experimental_uint8_t;

typedef uint32_t Hacl_Utils_Experimental_uint32_t;

typedef uint64_t Hacl_Utils_Experimental_uint64_t;

typedef uint8_t Hacl_Utils_Experimental_suint8_t;

typedef uint32_t Hacl_Utils_Experimental_suint32_t;

typedef uint64_t Hacl_Utils_Experimental_suint64_t;

typedef uint32_t *Hacl_Utils_Experimental_suint32_p;

typedef uint8_t *Hacl_Utils_Experimental_suint8_p;

uint8_t Hacl_Utils_Experimental_u8_to_s8(uint8_t a);

uint32_t Hacl_Utils_Experimental_u32_to_s32(uint32_t a);

uint64_t Hacl_Utils_Experimental_u32_to_s64(uint32_t a);

uint8_t Hacl_Utils_Experimental_s32_to_s8(uint32_t a);

uint64_t Hacl_Utils_Experimental_s32_to_s64(uint32_t a);

uint64_t Hacl_Utils_Experimental_u64_to_s64(uint64_t a);

void
Hacl_Utils_Experimental_upd4(
  uint32_t *buf,
  uint32_t idx,
  uint32_t a,
  uint32_t b,
  uint32_t c,
  uint32_t d
);

uint32_t Hacl_Utils_Experimental_rotate_right(uint32_t a, uint32_t b);

void Hacl_Utils_Experimental_be_bytes_of_sint32(uint8_t *output, uint32_t x);

uint32_t Hacl_Utils_Experimental_be_sint32_of_bytes(uint8_t *b);

void Hacl_Utils_Experimental_be_bytes_of_sint64(uint8_t *output, uint64_t x);

void Hacl_Utils_Experimental_xor_bytes(uint8_t *output, uint8_t *input, uint32_t len);

void Hacl_Utils_Experimental_be_bytes_of_uint32s(uint8_t *output, uint32_t *m, uint32_t len);

void Hacl_Utils_Experimental_be_uint32s_of_bytes(uint32_t *u, uint8_t *b, uint32_t len);
#endif
