/* This file was auto-generated by KreMLin! */
#ifndef __Random_H
#define __Random_H


#include "kremlib.h"
#include "drng.h"
#include "cpuid.h"

typedef uint8_t u8;

typedef uint32_t u32;

typedef uint64_t u64;

uint32_t random_uint32();

uint64_t random_uint64();

void random_bytes(uint8_t *rand, uint32_t n);

uint32_t randseed_uint32();

uint64_t randseed_uint64();
#endif
