/* This file was auto-generated by KreMLin! */
#ifndef __SHA2_256_H
#define __SHA2_256_H



#include "kremlib.h"
#include "testlib.h"

typedef uint8_t Hacl_Utils_Experimental_uint8_t;

typedef uint32_t Hacl_Utils_Experimental_uint32_t;

typedef uint64_t Hacl_Utils_Experimental_uint64_t;

typedef uint8_t Hacl_Utils_Experimental_suint8_t;

typedef uint32_t Hacl_Utils_Experimental_suint32_t;

typedef uint64_t Hacl_Utils_Experimental_suint64_t;

typedef uint32_t *Hacl_Utils_Experimental_suint32_p;

typedef uint8_t *Hacl_Utils_Experimental_suint8_p;

typedef uint8_t Hacl_Hash_SHA2_L256_uint8_t;

typedef uint32_t Hacl_Hash_SHA2_L256_uint32_t;

typedef uint64_t Hacl_Hash_SHA2_L256_uint64_t;

typedef uint8_t Hacl_Hash_SHA2_L256_suint8_t;

typedef uint32_t Hacl_Hash_SHA2_L256_suint32_t;

typedef uint64_t Hacl_Hash_SHA2_L256_suint64_t;

typedef uint32_t *Hacl_Hash_SHA2_L256_suint32_p;

typedef uint8_t *Hacl_Hash_SHA2_L256_suint8_p;

typedef uint8_t uint8_t;

typedef uint32_t uint32_t;

typedef uint64_t uint64_t;

typedef uint8_t suint8_t;

typedef uint32_t suint32_t;

typedef uint64_t suint64_t;

typedef uint32_t *suint32_p;

typedef uint8_t *suint8_p;

extern uint32_t hashsize_256;

extern uint32_t blocksize_256;

extern uint32_t size_state_256;

void sha2_init_256(uint32_t *state);

void sha2_update_256(uint32_t *state, uint8_t *data_8);

void sha2_update_multi_256(uint32_t *state, uint8_t *data, uint32_t n, uint32_t idx);

void sha2_update_last_256(uint32_t *state, uint8_t *data, uint32_t len);

void sha2_finish_256(uint32_t *state, uint8_t *hash);

void sha2_256(uint8_t *hash, uint8_t *input, uint32_t len);
#endif
