HACL_HOME = ..

all: $(HACL_HOME)/obj/libhacl.cmxa

include ../code/Makefile.local

# By default, we process all the files in the current directory. Here, we
# *extend* the set of relevant files with the alternative and experimental folders.
FSTAR_ROOTS += $(wildcard alternative/*.fst) $(wildcard experimental/*.fst)

OCAMLMKLIB = ocamlfind mklib -package fstarlib

$(HACL_HOME)/obj/libhacl.cmxa: $(ALL_CMX_FILES)
	ocamlmklib $^ -o $(HACL_HOME)/obj/libhacl
