/* This file auto-generated by KreMLin! */
#ifndef __Hacl_EC_Curve25519_AddAndDouble_H
#define __Hacl_EC_Curve25519_AddAndDouble_H


#include "Prims.h"
#include "FStar_Mul.h"
#include "FStar_Squash.h"
#include "FStar_StrongExcludedMiddle.h"
#include "FStar_List_Tot.h"
#include "FStar_Classical.h"
#include "FStar_ListProperties.h"
#include "FStar_SeqProperties.h"
#include "FStar_Math_Lemmas.h"
#include "FStar_BitVector.h"
#include "FStar_UInt.h"
#include "FStar_Int.h"
#include "FStar_FunctionalExtensionality.h"
#include "FStar_PropositionalExtensionality.h"
#include "FStar_PredicateExtensionality.h"
#include "FStar_TSet.h"
#include "FStar_Set.h"
#include "FStar_Map.h"
#include "FStar_Ghost.h"
#include "FStar_All.h"
#include "Hacl_UInt64.h"
#include "Hacl_UInt128.h"
#include "Hacl_UInt32.h"
#include "Hacl_UInt8.h"
#include "Hacl_Cast.h"
#include "FStar_Buffer.h"
#include "FStar_Buffer_Quantifiers.h"
#include "Hacl_EC_Curve25519_Parameters.h"
#include "Hacl_EC_Curve25519_Bigint.h"
#include "Hacl_EC_Curve25519_Utils.h"
#include "Hacl_EC_Curve25519_Bignum_Fproduct.h"
#include "Hacl_EC_Curve25519_Bignum_Fscalar.h"
#include "Hacl_EC_Curve25519_Bignum_Fdifference.h"
#include "Hacl_EC_Curve25519_Bignum_Fsum.h"
#include "Hacl_EC_Curve25519_Bignum_Modulo.h"
#include "Hacl_EC_Curve25519_Bignum.h"
#include "Hacl_EC_Curve25519_PPoint.h"
#include "kremlib.h"

void
Hacl_EC_Curve25519_AddAndDouble_double_and_add_0(
  Hacl_EC_Curve25519_PPoint_point pp,
  Hacl_EC_Curve25519_PPoint_point ppq,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point p_plus_q,
  Hacl_EC_Curve25519_PPoint_point q,
  uint64_t *tmp
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_2(
  FStar_HyperHeap_rid r,
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  Prims_prop (*sub)(FStar_Heap_aref x0),
  Prims_prop (*s)(FStar_Heap_aref x0)
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_3(
  FStar_HyperHeap_rid r,
  Prims_prop (*s)(FStar_Heap_aref x0),
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2,
  FStar_HyperStack_mem h3,
  FStar_HyperStack_mem h4
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_1(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2,
  FStar_HyperStack_mem h3,
  FStar_HyperStack_mem h4,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point pq
);

void
Hacl_EC_Curve25519_AddAndDouble_double_and_add_1(
  Hacl_EC_Curve25519_PPoint_point pp,
  Hacl_EC_Curve25519_PPoint_point ppq,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point p_plus_q,
  Hacl_EC_Curve25519_PPoint_point q,
  uint64_t *tmp
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_4(
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point p_
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_5(Hacl_EC_Curve25519_PPoint_point p, uint64_t *p_);

void
Hacl_EC_Curve25519_AddAndDouble_double_and_add_2(
  Hacl_EC_Curve25519_PPoint_point pp,
  Hacl_EC_Curve25519_PPoint_point ppq,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point pq,
  Hacl_EC_Curve25519_PPoint_point q,
  uint64_t *tmp
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_6(
  FStar_HyperHeap_rid r,
  Prims_prop (*s)(FStar_Heap_aref x0),
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2
);

void
Hacl_EC_Curve25519_AddAndDouble_double_and_add_3(
  Hacl_EC_Curve25519_PPoint_point pp,
  Hacl_EC_Curve25519_PPoint_point two_p_plus_q,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point pq,
  Hacl_EC_Curve25519_PPoint_point q,
  uint64_t *tmp
);

void
Hacl_EC_Curve25519_AddAndDouble_double_and_add_4(
  Hacl_EC_Curve25519_PPoint_point pp,
  Hacl_EC_Curve25519_PPoint_point ppq,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point pq,
  Hacl_EC_Curve25519_PPoint_point q,
  uint64_t *tmp
);

void
Hacl_EC_Curve25519_AddAndDouble_double_and_add_5(
  Hacl_EC_Curve25519_PPoint_point pp,
  Hacl_EC_Curve25519_PPoint_point ppq,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point pq,
  Hacl_EC_Curve25519_PPoint_point q,
  uint64_t *tmp
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_x(
  FStar_HyperHeap_rid r,
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2,
  FStar_HyperStack_mem h3,
  FStar_HyperStack_mem h4,
  FStar_HyperStack_mem h5,
  FStar_HyperStack_mem h6,
  FStar_HyperStack_mem h7,
  FStar_HyperStack_mem h8
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_y(
  FStar_HyperHeap_rid r,
  Prims_prop (*sub)(FStar_Heap_aref x0),
  Prims_prop (*s)(FStar_Heap_aref x0),
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_z(
  FStar_HyperHeap_rid r,
  FStar_HyperHeap_rid r_,
  Prims_prop (*s)(FStar_Heap_aref x0),
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_w(
  Hacl_EC_Curve25519_PPoint_point pp,
  Hacl_EC_Curve25519_PPoint_point ppq,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point pq
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_xx(
  FStar_HyperHeap_rid r,
  Prims_prop (*s)(FStar_Heap_aref x0),
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2,
  FStar_HyperStack_mem h3,
  FStar_HyperStack_mem h4,
  FStar_HyperStack_mem h5,
  FStar_HyperStack_mem h6,
  FStar_HyperStack_mem h7,
  FStar_HyperStack_mem h8
);

void
Hacl_EC_Curve25519_AddAndDouble_double_and_add_(
  Hacl_EC_Curve25519_PPoint_point pp,
  Hacl_EC_Curve25519_PPoint_point ppq,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point pq,
  Hacl_EC_Curve25519_PPoint_point q,
  uint64_t *tmp
);

void
Hacl_EC_Curve25519_AddAndDouble_lemma_helper_7(
  FStar_HyperStack_mem hinit,
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  FStar_HyperStack_mem h2,
  FStar_HyperStack_mem hfin,
  FStar_HyperHeap_rid r
);

void
Hacl_EC_Curve25519_AddAndDouble_double_and_add(
  Hacl_EC_Curve25519_PPoint_point two_p,
  Hacl_EC_Curve25519_PPoint_point two_p_plus_q,
  Hacl_EC_Curve25519_PPoint_point p,
  Hacl_EC_Curve25519_PPoint_point p_plus_q,
  Hacl_EC_Curve25519_PPoint_point q
);
#endif
