#include "Hacl_Constants.h"

Prims_int Hacl_Constants_crypto_box_NONCEBYTES;

Prims_int Hacl_Constants_crypto_box_PUBLICKEYBYTES;

Prims_int Hacl_Constants_crypto_box_SECRETKEYBYTES;

Prims_int Hacl_Constants_crypto_box_MACBYTES;

Prims_int Hacl_Constants_crypto_secretbox_NONCEBYTES;

Prims_int Hacl_Constants_crypto_secretbox_KEYBYTES;

Prims_int Hacl_Constants_crypto_secretbox_MACBYTES;

