/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: /Users/bhargava/Desktop/repositories/kremlin/krml -I /Users/bhargava/Desktop/repositories/hacl-star/code/lib/kremlin -I /Users/bhargava/Desktop/repositories/kremlin/kremlib/compat -I /Users/bhargava/Desktop/repositories/hacl-star/specs -I . -ccopt -march=native -verbose -ldopt -flto -I ../bignum -tmpdir x25519-c -no-prefix Hacl.Test.X25519 -bundle Hacl.Test.X25519=* -minimal -add-include "kremlib.h" x25519-c/Hacl_Curve25519.c x25519-c/out.krml -o x25519.exe
 * F* version: 2441c5c2
 * KreMLin version: 7661d65b
 */


#ifndef __Hacl_Test_X25519_H
#define __Hacl_Test_X25519_H


#include "kremlib.h"

extern FStar_UInt128_uint128 FStar_Int_Cast_Full_uint64_to_uint128(uint64_t x0);

exit_code main();

#define __Hacl_Test_X25519_H_DEFINED
#endif
