/* This file auto-generated by KreMLin! */
#ifndef __Hacl_Bignum_Bigint_H
#define __Hacl_Bignum_Bigint_H


#include "Prims.h"
#include "FStar_Mul.h"
#include "FStar_Squash.h"
#include "FStar_StrongExcludedMiddle.h"
#include "FStar_List_Tot.h"
#include "FStar_Classical.h"
#include "FStar_ListProperties.h"
#include "FStar_SeqProperties.h"
#include "FStar_Math_Lemmas.h"
#include "FStar_BitVector.h"
#include "FStar_UInt.h"
#include "FStar_Int.h"
#include "FStar_FunctionalExtensionality.h"
#include "FStar_PropositionalExtensionality.h"
#include "FStar_PredicateExtensionality.h"
#include "FStar_TSet.h"
#include "FStar_Set.h"
#include "FStar_Map.h"
#include "FStar_Ghost.h"
#include "FStar_All.h"
#include "Hacl_UInt64.h"
#include "Hacl_UInt128.h"
#include "Hacl_UInt32.h"
#include "Hacl_UInt8.h"
#include "Hacl_Cast.h"
#include "Hacl_Bignum_Constants.h"
#include "FStar_Buffer.h"
#include "Hacl_Bignum_Parameters.h"
#include "Hacl_Bignum_Predicates.h"
#include "Hacl_Bignum_Limb.h"
#include "Hacl_Bignum_Wide.h"
#include "kremlib.h"
#include "testlib.h"

Prims_nat Hacl_Bignum_Bigint_bitweight(Prims_nat n);

Prims_nat Hacl_Bignum_Bigint_eval_(FStar_HyperStack_mem h, uint64_t *b, Prims_nat i);

Prims_nat Hacl_Bignum_Bigint_eval(FStar_HyperStack_mem h, uint64_t *b);

Prims_nat
Hacl_Bignum_Bigint_eval_wide_(FStar_HyperStack_mem h, FStar_UInt128_t *b, Prims_nat i);

Prims_nat Hacl_Bignum_Bigint_eval_wide(FStar_HyperStack_mem h, FStar_UInt128_t *b);
#endif
